#!/usr/bin/env python3
"""Sweep --common_beta on the pair-exam fixture.

Partial keep of the common component:
``tgt = (1−β)·(h0 ± a) + β·h±``. β=0 is pair-odd (banned). β=1 is the
raw poles. The exam is the smallest β that still PASSES exam_divergent
with leftover_bipolar leak_frac < 0.

CPU only. No Hub, no GPU, no Music 3 weights. Does not change the live
trainer default (still ``--lm_target v9`` / ``--pole_mode hidden``).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.exam import (
    COMMON_BETA_GRID,
    common_beta_seed_check,
    common_beta_sweep,
    floatable,
    smallest_divergent_pass_beta,
)
from conceptmod.textsliders.slider_targets import COMMON_BETA_EXAM
from conceptmod.textsliders.train_lm_slider_music3 import parse_args as parse_train_args


DEFAULT_OUT = _REPO / "docs" / "lm-common-beta-exam"


def _f(value, spec: str, empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _pass(flag: bool) -> str:
    return "**PASS**" if flag else "**FAIL**"


def plot_sweep(sweep: list[dict], path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7.6, 4.6))
    xs = [r["common_beta"] for r in sweep]
    ys = [r["leak_frac"] for r in sweep]
    colors = ["#1e8449" if r["exam_divergent"] else "#c0392b" for r in sweep]
    ax.plot(xs, ys, color="#7f8c8d", lw=1.1, zorder=2)
    ax.scatter(xs, ys, c=colors, s=64, zorder=3, edgecolors="white", linewidths=0.6)
    ax.axhline(0.0, color="#2c3e50", ls="--", lw=0.9)
    ax.axvline(0.0, color="#7f8c8d", ls=":", lw=0.8)
    ax.axvline(1.0, color="#7f8c8d", ls=":", lw=0.8)
    ax.scatter([], [], c="#1e8449", s=64, label="exam_divergent PASS")
    ax.scatter([], [], c="#c0392b", s=64, label="exam_divergent FAIL")
    ax.set_xlabel("β  —  tgt = (1−β)·(h0 ± a) + β·h±")
    ax.set_ylabel("leak_frac = cos(d+, d−) of the fitted ±1 student")
    ax.set_title("green passes divergent; below the dashed line is leak_frac < 0")
    ax.set_xlim(-0.04, 1.04)
    ax.set_ylim(-1.08, 0.25)
    ax.grid(alpha=0.25)
    ax.legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_report(blob: dict, path: Path) -> None:
    sweep = blob["sweep"]
    hit = blob["hit"]
    first = smallest_divergent_pass_beta(sweep)
    clear = smallest_divergent_pass_beta(sweep, clear=True)
    train = parse_train_args(["--prompts", "x.yaml"])
    lines = [
        "# Partial keep of c: --common_beta on the pair exam",
        "",
        "Generated by `analysis/slider2d/run_lm_common_beta.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default.",
        "",
        "The interpolation already exists live as `--lm_target symmetric",
        f"--common_beta β`. Default remains `{train.lm_target}` / `{train.pole_mode}`",
        f"with `--common_beta {train.common_beta}`. `--lm_target v9` ignores the",
        "flag (κ=0, full pair-odd).",
        "",
        "    tgt(±1) = (1 − β)·(h0 ± a) + β·h±",
        "            = h0 ± a + β·c",
        "",
        "β=0 is pair-odd (`t± = h0 ± a`). Energy sings a blend. Banned.",
        "β=1 is the raw caption poles. Those pass `exam_divergent` and sit at",
        "`leak_frac ≥ 0` on energy-v4 (the two tracks share a small even piece).",
        "",
        "The exam: smallest β (most odd) that still **PASSES** `exam_divergent`,",
        "and that row's `leak_frac = cos(d+, d−)` of the fitted ±1 student",
        "(`leftover_bipolar`). More negative is better only if divergent still",
        "passes. A recipe at `leak_frac ≈ −1` that fails divergent is the known",
        "Goodhart, not a win. Passing `exam_close` is desired; divergent +",
        "negative `leak_frac` is the gate. Leftover leak is unused ê on the",
        "`unused_e` cell — `c` is not that axis, so this dial does not eat it.",
        "",
        "## Sweep",
        "",
        "| β | exam_divergent | exam_close | leak_frac | leftover leak | same-words | swing |",
        "|---:|:---:|:---:|---:|---:|---:|---:|",
    ]
    for row in sweep:
        lines.append(
            f"| {row['common_beta']:.2f} | {_pass(row['exam_divergent'])} | "
            f"{_pass(row['exam_close'])} | {row['leak_frac']:+.3f} | "
            f"{_f(row['leftover_leak'], '+.3f')} | "
            f"{row['divergent_match']:.2f} | {row['divergent_swing']:+.2f} |"
        )
    lines += [
        "",
        "![common beta](lm-common-beta-exam/common-beta.png)",
        "",
        "## Verdict",
        "",
    ]
    if first is None:
        lines += [
            "No β in the grid passed `exam_divergent`. That should not happen:",
            "β=1 is the raw poles and already passes on this fixture.",
            "",
        ]
    elif hit is None:
        lines += [
            f"Smallest β that still PASSES `exam_divergent` is "
            f"**β = {first['common_beta']:.2f}**, with "
            f"`leak_frac` = {first['leak_frac']:+.3f}.",
            "That `leak_frac` is **not** negative. No β < 1 goes negative",
            "while passing divergent on this fixture. The known Goodhart is",
            "the other side of the line: β=0 has `leak_frac` ≈ −1 and fails.",
            "Do not ship a live `--lm_target` for an intermediate β.",
            "",
            f"- exam_close at that β: {_pass(first['exam_close'])}",
            f"- leftover leak (unused ê): {_f(first['leftover_leak'], '+.3f')}",
            f"- why divergent: {first['divergent_reason']}",
            "",
        ]
    else:
        near = ", ".join(hit.get("divergent_near_gate") or []) or "none"
        lines += [
            f"Hit: **β = {hit['common_beta']:.2f}** is the smallest β that",
            f"PASSES `exam_divergent` with `leak_frac` = {hit['leak_frac']:+.3f} < 0.",
            "That is a train recipe, not a data pin: `--lm_target symmetric",
            f"--common_beta {hit['common_beta']:g} --pole_mode hidden`.",
            "The live default is unchanged.",
            "",
            f"- exam_close: {_pass(hit['exam_close'])}",
            f"- leftover leak (unused ê): {_f(hit['leftover_leak'], '+.3f')}",
            f"- same-words: {hit['divergent_match']:.2f}",
            f"- swing kept: {hit['divergent_swing']:+.2f}",
            f"- near-gate: {near}",
            "",
        ]
        if clear is not None and float(clear["common_beta"]) != float(hit["common_beta"]):
            lines += [
                f"That first pass sits near a gate. The first **clear** seed-0 pass",
                f"(no near-gate column) is **β = {clear['common_beta']:.2f}**,",
                f"`leak_frac` = {clear['leak_frac']:+.3f}, exam_close",
                f"{_pass(clear['exam_close'])}.",
                "",
            ]
        card = blob.get("train_card") or {}
        if card:
            lines += [
                "## Train card",
                "",
                f"`--lm_target common_beta --pole_mode hidden` freezes",
                f"**β = {card['common_beta']:.2f}** (`leak_frac` = "
                f"{card['leak_frac']:+.3f} on seed 0). That is the first β",
                "that PASSES `exam_divergent` on seeds 0/1/2 without a",
                "near-gate column. Equivalent: `--lm_target symmetric",
                f"--common_beta {card['common_beta']:g} --pole_mode hidden`.",
                "Live default stays `--lm_target v9` / `--pole_mode hidden`.",
                "Not a live listen.",
                "",
            ]
        seeds = blob.get("seed_check") or []
        if seeds:
            lines += [
                "## Seed check (divergent / close)",
                "",
                "| seed | β | exam_divergent | exam_close | leak_frac | same-words |",
                "|---:|---:|:---:|:---:|---:|---:|",
            ]
            for row in seeds:
                lines.append(
                    f"| {row['seed']} | {row['common_beta']:.2f} | "
                    f"{_pass(row['exam_divergent'])} | {_pass(row['exam_close'])} | "
                    f"{row['leak_frac']:+.3f} | {row['divergent_match']:.2f} |"
                )
            lines.append("")
    passing = [r for r in sweep if r["exam_divergent"] and r["leak_frac"] < 0]
    if passing and hit is not None:
        lines += [
            "Every β in the grid that passes divergent with negative leak_frac:",
            "",
            "| β | leak_frac | exam_close | leftover leak |",
            "|---:|---:|:---:|---:|",
        ]
        for row in passing:
            lines.append(
                f"| {row['common_beta']:.2f} | {row['leak_frac']:+.3f} | "
                f"{_pass(row['exam_close'])} | {_f(row['leftover_leak'], '+.3f')} |"
            )
        lines.append("")
    lines += [
        "Leftover unused ê lives in `a`, not `c`. Interpolating the common",
        "component cannot clear the unused-ê sheet; leftover leak stays in",
        "the faithful / pair-odd band (~0.23) across the whole ladder.",
        "",
        "## What this is not",
        "",
        "- Not `faithful_attrs`. That is unused gender written into captions.",
        "- Not pair-odd / `_sub_e` / midpoint / hold-ê / hub / project.",
        "  Those delete `c` (`t± = h0 ± a`) and fail divergent or have",
        "  `leak_frac ≈ −1`.",
        "- Not a live listen. These numbers are the CPU pair-exam fixture.",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_common_beta.py "
        "--out docs/lm-common-beta-exam",
        "PYTHONPATH=. pytest tests/test_lm_pair_exam.py -q -k common_beta",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights.",
        "",
        f"Seed `{blob['seed']}`, `{blob['steps']}` Adam steps, grid "
        f"`{', '.join(f'{b:g}' for b in blob['grid'])}`.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--grid",
        type=float,
        nargs="+",
        default=list(COMMON_BETA_GRID),
        help="β values to score (default: the published exam grid)",
    )
    args = parser.parse_args(argv)

    out = args.out
    out.mkdir(parents=True, exist_ok=True)
    grid = tuple(float(b) for b in args.grid)
    sweep = common_beta_sweep(grid, steps=args.steps, seed=args.seed)
    first = smallest_divergent_pass_beta(sweep)
    clear = smallest_divergent_pass_beta(sweep, clear=True)
    hit = None
    if first is not None and float(first["leak_frac"]) < 0.0:
        hit = first
    seed_check = common_beta_seed_check(
        (0.08, 0.15, float(COMMON_BETA_EXAM)),
        (0, 1, 2),
        steps=args.steps,
    )
    card_row = next(
        (r for r in sweep if abs(float(r["common_beta"]) - float(COMMON_BETA_EXAM)) < 1e-9),
        None,
    )
    train = parse_train_args(["--prompts", "x.yaml"])
    blob = {
        "steps": args.steps,
        "seed": args.seed,
        "grid": list(grid),
        "sweep": [floatable(r) for r in sweep],
        "smallest_divergent_pass": floatable(first) if first is not None else None,
        "first_clear_divergent_pass": floatable(clear) if clear is not None else None,
        "hit": floatable(hit) if hit is not None else None,
        "seed_check": [floatable(r) for r in seed_check],
        "train_card": (
            {
                "lm_target": "common_beta",
                "pole_mode": "hidden",
                "common_beta": float(COMMON_BETA_EXAM),
                "leak_frac": float(card_row["leak_frac"]) if card_row is not None else None,
                "exam_divergent": bool(card_row["exam_divergent"]) if card_row is not None else None,
                "exam_close": bool(card_row["exam_close"]) if card_row is not None else None,
                "leftover_leak": card_row["leftover_leak"] if card_row is not None else None,
            }
            if card_row is not None
            else None
        ),
        "live_default": {
            "lm_target": train.lm_target,
            "pole_mode": train.pole_mode,
            "common_beta": float(train.common_beta),
        },
    }
    (out / "metrics.json").write_text(json.dumps(blob, indent=2) + "\n", encoding="utf-8")
    plot_sweep(sweep, out / "common-beta.png")
    write_report(blob, out.parent / "lm-common-beta-exam.md")
    for row in sweep:
        tag = "PASS" if row["exam_divergent"] else "FAIL"
        print(
            f"β={row['common_beta']:.2f}  divergent={tag:4s}  "
            f"close={'PASS' if row['exam_close'] else 'FAIL':4s}  "
            f"leak_frac={row['leak_frac']:+.3f}  "
            f"leftover={row['leftover_leak']}"
        )
    if hit is not None:
        print(
            f"HIT β={hit['common_beta']:.2f} leak_frac={hit['leak_frac']:+.3f} "
            f"exam_close={hit['exam_close']}"
        )
    elif first is not None:
        print(
            f"no hit: first divergent PASS is β={first['common_beta']:.2f} "
            f"leak_frac={first['leak_frac']:+.3f}"
        )
    else:
        print("no β in the grid passed exam_divergent")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
