#!/usr/bin/env python3
"""Plus+neu exam: cover vs neu_hold on the UNI scale. Separate scale."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.plus_exam import PLUS_COVER_MIN, PLUS_OFF_MAX
from analysis.slider2d.plus_neu_exam import (
    PLUS_NEU_CELLS,
    PLUS_NEU_HOLD_MIN,
    PLUS_NEU_RECIPES,
    plus_neu_exam_table,
    plus_neu_helps,
    plus_neu_rank,
    plus_neu_sort_key,
)


DEFAULT_OUT = _REPO / "docs" / "lm-plus-neu-exam"


def _f(value, spec: str = ".3f", empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def plot_plus_neu_scale(table: dict[str, list[dict]], path: Path) -> None:
    """cover vs neu_hold. Size/color = off-caption. Want-box is high both."""
    fig, ax = plt.subplots(figsize=(8.6, 5.6))
    marks = {"divergent": "o", "close": "s", "unused_e": "^"}
    colors = {
        "faithful_plus_neu": "#1e8449",
        "faithful_plus": "#7d3c98",
        "leftover_gate_bipolar": "#2471a3",
        "faithful_even_blend": "#b9770e",
        "pair_odd_midpoint": "#c0392b",
    }
    want = Rectangle(
        (PLUS_COVER_MIN, PLUS_NEU_HOLD_MIN),
        1.0 - PLUS_COVER_MIN,
        1.0 - PLUS_NEU_HOLD_MIN,
        facecolor="#d5f5e3",
        edgecolor="#1e8449",
        lw=1.0,
        alpha=0.55,
        zorder=1,
        label="want-box (high cover AND high neu_hold)",
    )
    ax.add_patch(want)
    for cell, rows in table.items():
        if cell == "unused_e":
            continue
        for row in rows:
            off = max(0.0, float(row["off_caption"]))
            size = 70 + 520 * min(1.0, off / 0.12)
            ax.scatter(
                [row["cover"]],
                [row["neu_hold"]],
                c=[off],
                cmap="YlOrRd",
                vmin=0.0,
                vmax=max(PLUS_OFF_MAX, 0.12),
                marker=marks.get(cell, "o"),
                s=size,
                zorder=3,
                edgecolors=colors.get(row["name"], "#7f8c8d"),
                linewidths=1.2,
            )
            ax.annotate(
                f"{row['name']}\n{cell}",
                (row["cover"], row["neu_hold"]),
                fontsize=6.2,
                xytext=(5, 4),
                textcoords="offset points",
            )
    for name, color in colors.items():
        ax.scatter([], [], c=color, marker="o", s=58, label=name)
    ax.axvline(PLUS_COVER_MIN, color="#7f8c8d", ls=":", lw=0.9)
    ax.axhline(PLUS_NEU_HOLD_MIN, color="#7f8c8d", ls=":", lw=0.9)
    ax.set_xlabel("cover of the + state  [0, 1]  (higher is better)")
    ax.set_ylabel("neu_hold at scale 0  [0, 1]  (higher is better)")
    ax.set_title(
        "Plus+neu scale — not the bipolar board\n"
        "cover vs neu_hold; marker size/color = off-caption on +"
    )
    ax.set_xlim(-0.02, 1.05)
    ax.set_ylim(-0.02, 1.05)
    ax.grid(alpha=0.25)
    cbar = fig.colorbar(
        plt.cm.ScalarMappable(
            cmap="YlOrRd",
            norm=plt.Normalize(vmin=0.0, vmax=max(PLUS_OFF_MAX, 0.12)),
        ),
        ax=ax,
        fraction=0.046,
        pad=0.04,
    )
    cbar.set_label("off-caption on the + continuation (lower is better)")
    ax.legend(fontsize=7.0, loc="lower left")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def _train_label(row: dict) -> str:
    if row.get("plus_neu"):
        return "plus+neu"
    if row.get("plus_only"):
        return "plus-only"
    return "bipolar ±"


def write_markdown(
    table: dict[str, list[dict]],
    verdict: dict,
    ranked: list[dict],
    path: Path,
) -> None:
    beats = "yes" if verdict["beats_plus_on_neu_hold"] else "no"
    keeps = "yes" if verdict["keeps_plus_cover"] else "no"
    lines = [
        "# Plus+neu exam: cover +, hold 0 on the song",
        "",
        "Generated by `analysis/slider2d/run_lm_plus_neu_exam.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default",
        "(`--lm_target v9` / `--pole_mode hidden`). This is a **separate",
        "scale** from the plus-only exam, pair-exam, leftover-sheet `leak_frac`,",
        "and the compiled bipolar board. Those pages are not updated here.",
        "",
        "`faithful_plus` (+1 → leftover-gated `h+` only) is the live garble",
        "card: no neu hold, the student left the song. UNI trains the",
        "positive and the neutral only. No minus teacher. Not bipolar faithful.",
        "",
        f"**Does plus+neu beat `faithful_plus` on neu_hold? `{beats}`** — and",
        f"**does it keep + cover? `{keeps}`** — from the three scored numbers",
        "on the same CPU fixture, not from an essay.",
        "",
        "## Three scored numbers",
        "",
        "1. **cover** of the + state (same as plus-only):",
        "",
        "   `cover = min(overlap_with_pos, 1 − blend_toward_mid)` in `[0, 1]`.",
        "",
        f"   Gate: `≥ {PLUS_COVER_MIN}`. Higher is better.",
        "2. **off-caption** on the + continuation: words neither the + caption",
        "   nor the pair's shared song sings. Shared song is lyrics plus tokens",
        "   both pole captions sing. Singing the − pole's unique track words",
        f"   is off-caption here. Gate: `≤ {PLUS_OFF_MAX}`. Lower is better.",
        "3. **neu_hold**: student at scale 0 stays on the yaml lyrics /",
        "   neutral caption:",
        "",
        "   `neu_hold = min(overlap_with_neu, 1 − drift_from_neu)` in `[0, 1]`.",
        "",
        "   `overlap_with_neu` is the share of the scale-0 continuation that",
        "   the lyrics field or the neu caption itself sings.",
        "   `drift_from_neu` is",
        "   `‖s0 − neu‖ / (‖s0 − neu‖ + min(‖s0 − pos‖, ‖s0 − mid‖))` — 0 at",
        f"   neu, 1 at pos or at mid. Gate: `≥ {PLUS_NEU_HOLD_MIN}`.",
        "",
        "A hit is all three. Not scored: `leak_frac`, collapse, pair-odd,",
        "minus overlap, `exam_score`. −1 is an unscored canary.",
        "",
        "The CPU student has a free origin (`δ(σ) = σ·w + |σ|·w_even + w0`)",
        "so scale 0 can leave the song. UNI's `MSE(0)` pins `w0`; plus-only",
        "and bipolar do not. A live multiplier LoRA has no `w0`; the live",
        "card is still `MSE(+) + MSE(0)` onto raw `h+` / `h0`.",
        "",
        "## Train card (opt-in)",
        "",
        "`--lm_target faithful_plus_neu --pole_mode hidden`. Teacher is raw",
        "`h+` (never leftover-gated, even if `leak_*` exists). Student +1",
        "fits that + caption. Student scale 0 fits `h0`. No pair-odd, no",
        "`h0 ± a`, no minus MSE. Sidecar records `lm_target` and `plus_neu`.",
        "Default stays `--lm_target v9` / `--pole_mode hidden`.",
        "`faithful_plus` is unchanged (still plus-only, still the garble card).",
        "Last-token UNI is the gender / tempo card. Whole-prefix hold and",
        "lyric-token hold live on [lm-lyric-hold.md](lm-lyric-hold.md).",
        "",
        "```bash",
        "CUDA_VISIBLE_DEVICES=N python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name energy-lm-uni-v1 \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
        "  --lm_target faithful_plus_neu --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0 --device 0",
        "```",
        "",
        "v4 yaml is the fixture rank. Uni yamls can swap in later. The yaml",
        "is not rewritten. No live listen on this branch.",
        "",
        "## Combined rank (divergent + close)",
        "",
        "In-box first (hit on both required pairs), then neu_hold, then",
        "cover, then off-caption. Averages over the two required cells.",
        "`unused_e` is logged below and is not in this rank.",
        "",
        "| rank | recipe | train | in-box | neu_hold | cover | off-caption | hit Δ | hit close |",
        "|---:|---|---|---|---:|---:|---:|---|---|",
    ]
    for row in ranked:
        lines.append(
            "| {rank} | `{name}` | {train} | {box} | {hold} | {cover} | {off} | {hd} | {hc} |".format(
                rank=row["rank"],
                name=row["name"],
                train=_train_label(row),
                box="**yes**" if row["in_box"] else "—",
                hold=_f(row["neu_hold"]),
                cover=_f(row["cover"]),
                off=_f(row["off_caption"]),
                hd="**HIT**" if row["hit_divergent"] else "—",
                hc="**HIT**" if row["hit_close"] else "—",
            )
        )
    lines += [
        "",
        "## The board (400 Adam steps, seed 0)",
        "",
        "This is the plus+neu scale, not the bipolar board. `faithful_plus`",
        "is the leftover-gated plus-only garble card. `leftover_gate_bipolar`",
        "is the current `faithful` / leftover-gate +/− teacher.",
        "`faithful_even_blend` is the v21 bipolar even-blend (`α = 0.5`).",
        "`pair_odd_midpoint` is the known fail.",
        "",
    ]
    for cell in PLUS_NEU_CELLS:
        rows = sorted(table[cell], key=plus_neu_sort_key)
        lines += [
            f"### `{cell}`",
            "",
            "| recipe | train | cover | off-caption | neu_hold | overlap+ | overlap0 | hit |",
            "|---|---|---:|---:|---:|---:|---:|---|",
        ]
        for row in rows:
            lines.append(
                "| `{name}` | {train} | {cover} | {off} | {hold} | {ov} | {ov0} | {hit} |".format(
                    name=row["name"],
                    train=_train_label(row),
                    cover=_f(row["cover"]),
                    off=_f(row["off_caption"]),
                    hold=_f(row["neu_hold"]),
                    ov=_f(row["overlap_pos"]),
                    ov0=_f(row["overlap_neu"]),
                    hit="**HIT**" if row["hit"] else "—",
                )
            )
        lines.append("")
    lines += [
        "![cover vs neu_hold on the plus+neu scale](lm-plus-neu-exam/plus-neu-scale.png)",
        "",
        "Want-box is high cover AND high neu_hold. Marker size and color are",
        "off-caption on the + continuation (smaller / cooler is cleaner).",
        "Title says this is the plus+neu scale, not the bipolar board.",
        "Required pairs only on the chart; `unused_e` stays in the table.",
        "",
        "## Unscored canary: what −1 does",
        "",
        "Inference may still expose a −1 fader. Plus+neu does not train it.",
        "Logged here only. Not a score. `dangerous` is same-dir (landed on +)",
        "or −1 off-caption above the 0.05 suggestion.",
        "",
        "| cell | recipe | −1 landed | −1 overlap with − | −1 off-caption | dangerous? |",
        "|---|---|---|---:|---:|---|",
    ]
    for cell, rows in table.items():
        for row in rows:
            can = row["canary"]
            lines.append(
                "| `{cell}` | `{name}` | {land} | {ov} | {off} | {dang} |".format(
                    cell=cell,
                    name=row["name"],
                    land=can["minus_landed"],
                    ov=_f(can["minus_overlap_neg"]),
                    off=_f(can["minus_off_caption"]),
                    dang="**yes**" if can["dangerous"] else "no",
                )
            )
    lines += [
        "",
        "## What the numbers say",
        "",
        "- Plus+neu hits both required pairs (divergent, close): "
        f"**{'yes' if all(verdict['uni_hits_required']) else 'no'}**.",
        "- Plus-only (`faithful_plus`) hits both required pairs: "
        f"**{'yes' if all(verdict['plus_hits_required']) else 'no'}**.",
        "- Plus+neu beats `faithful_plus` on neu_hold on both required pairs: "
        f"**{beats}** "
        f"(UNI {', '.join(_f(x) for x in verdict['uni_neu_hold'])} vs "
        f"plus-only {', '.join(_f(x) for x in verdict['plus_neu_hold'])}).",
        "- Plus+neu keeps + cover: "
        f"**{keeps}** "
        f"(UNI {', '.join(_f(x) for x in verdict['uni_cover'])} vs "
        f"plus-only {', '.join(_f(x) for x in verdict['plus_cover'])}).",
        "",
        f"**Answer: neu_hold {beats}, cover {keeps}.** Training + and 0 "
        + (
            "holds the origin on the lyrics / neu caption. Plus-only still "
            "covers + but lets scale 0 leave the song — the live garble."
            if verdict["beats_plus_on_neu_hold"]
            else "does not beat leftover-gated plus-only on neu_hold on this fixture."
        ),
        "",
        "## Related cells (not this scale)",
        "",
        "- [lm-plus-exam.md](lm-plus-exam.md) — plus-only cover / off-caption.",
        "- [lm-lyric-recall.md](lm-lyric-recall.md) — existing-metric OOD + `faithful_plus_neu` bug hunt.",
        "- [lm-lyric-hold.md](lm-lyric-hold.md) — grit lyrics vs gender_move scoreboard.",
        "- [lm-pair-exam.md](lm-pair-exam.md) — bipolar continuation gates.",
        "- [lm-even-leftover.md](lm-even-leftover.md) — leftover-sheet `leak_frac`.",
        "- [lm-2d-scoreboard.md](lm-2d-scoreboard.md) — compiled bipolar board.",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_plus_neu_exam.py --out docs/lm-plus-neu-exam",
        "PYTHONPATH=. pytest tests/test_lm_plus_neu_exam.py tests/test_lm_plus_exam.py tests/test_lm_trainer_v9.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights. Seed `0`, `400` Adam steps.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table = plus_neu_exam_table(steps=args.steps, seed=args.seed)
    verdict = plus_neu_helps(table)
    ranked = plus_neu_rank(table)
    blob = {
        "scale": "plus+neu",
        "not_the_bipolar_board": True,
        "scored": ["cover", "off_caption", "neu_hold"],
        "not_scored": [
            "leak_frac",
            "collapse",
            "pair_odd_cos",
            "minus_overlap",
            "exam_score",
        ],
        "gates": {
            "cover_min": PLUS_COVER_MIN,
            "off_caption_max": PLUS_OFF_MAX,
            "neu_hold_min": PLUS_NEU_HOLD_MIN,
        },
        "recipes": [c["name"] for c in PLUS_NEU_RECIPES],
        "cells": list(PLUS_NEU_CELLS),
        "steps": args.steps,
        "seed": args.seed,
        "helps": verdict,
        "rank": ranked,
        "rows": table,
    }
    (args.out / "metrics.json").write_text(
        json.dumps(blob, indent=2, default=str) + "\n", encoding="utf-8"
    )
    plot_plus_neu_scale(table, args.out / "plus-neu-scale.png")
    write_markdown(table, verdict, ranked, _REPO / "docs" / "lm-plus-neu-exam.md")
    print(f"wrote {args.out}  beats_hold={verdict['beats_plus_on_neu_hold']} keeps_cover={verdict['keeps_plus_cover']}")


if __name__ == "__main__":
    main()
