#!/usr/bin/env python3
"""OOD detection with existing metrics + faithful_plus_neu bug hunt."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.exam import (
    EXAM_COHERENCE,
    EXAM_MATCH_KEPT,
    EXAM_ROLL_OFF_MAX,
    EXAM_ROLL_OVERLAP,
)
from analysis.slider2d.lyric_recall import (
    EXISTING_OOD_METRICS,
    LYRIC_CELLS,
    LYRIC_RECIPES,
    existing_ood_verdict,
    lyric_exam_table,
    lyric_rank,
    lyric_verdict,
)
from analysis.slider2d.plus_exam import PLUS_COVER_MIN, PLUS_OFF_MAX
from analysis.slider2d.plus_neu_exam import PLUS_NEU_HOLD_MIN
from analysis.slider2d.sheet import GARBLE_MAX


DEFAULT_OUT = _REPO / "docs" / "lm-lyric-recall"

METRIC_LABELS = {
    "plus_off_caption": "plus-exam off_caption",
    "pair_off_corpus": "pair-exam off_corpus",
    "pair_same_words": "pair-exam same_words",
    "pair_coherence": "pair-exam coherence",
    "sheet_garble": "sheet garble",
    "sheet_lyric_mass": "sheet lyric_mass / vs lyric sheet",
}


def _f(value, spec: str = ".3f", empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _flag(flagged: bool) -> str:
    return "**FLAG**" if flagged else "—"


def _useful(key: str, useful: list[str]) -> str:
    return "**yes**" if key in useful else "no"


def plot_existing_ood(ood: dict, path: Path) -> None:
    """Existing metrics on UNI grit vs gender, last-hidden vs prefix sung."""
    fig, axes = plt.subplots(1, 2, figsize=(10.2, 4.8), sharey=True)
    names = list(EXISTING_OOD_METRICS)
    labels = [METRIC_LABELS[n] for n in names]
    y = np.arange(len(names))
    for ax, surface, title in (
        (axes[0], "last_hidden", "scored on last-hidden continuation"),
        (axes[1], "prefix_sung", "scored on prefix sung line"),
    ):
        grit = [ood["grit"][surface]["values"][n] for n in names]
        gender = [ood["gender"][surface]["values"][n] for n in names]
        ax.barh(y - 0.18, grit, height=0.36, color="#7d3c98", label="grit-like UNI")
        ax.barh(y + 0.18, gender, height=0.36, color="#1e8449", label="gender-like UNI")
        ax.set_yticks(y)
        ax.set_yticklabels(labels, fontsize=8)
        ax.set_xlim(0.0, 1.05)
        ax.set_title(title, fontsize=10)
        ax.grid(axis="x", alpha=0.25)
    axes[1].legend(fontsize=8, loc="lower right")
    fig.suptitle(
        "Existing metrics on UNI +1 — not a new scale\n"
        "only prefix sung lyric_mass splits grit shred from gender keep",
        fontsize=11,
    )
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_markdown(
    table: dict[str, list[dict]],
    verdict: dict,
    ranked: list[dict],
    ood: dict,
    path: Path,
) -> None:
    grit_p = ood["grit"]["prefix_sung"]
    gender_p = ood["gender"]["prefix_sung"]
    grit_l = ood["grit"]["last_hidden"]
    gender_l = ood["gender"]["last_hidden"]
    useful = ood["useful"]
    lines = [
        "# OOD detection + `faithful_plus_neu` bug hunt",
        "",
        "Generated by `analysis/slider2d/run_lm_lyric_recall.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default",
        "(`--lm_target v9` / `--pole_mode hidden`). This is **not** a new",
        "lyric-recall leaderboard. We already have cover / neu_hold /",
        "off-caption / pair-exam / sheet. The job is: which of those would",
        "have flagged grit-like +1 lyric shred vs gender/tempo keep, and",
        "which `faithful_plus_neu` implementation mistakes would cause OOD",
        "even if the math (MSE +1 last → raw h+, MSE 0 → h0, no minus) is",
        "right.",
        "",
        "Two failures, do not mix:",
        "",
        "1. **Two-song yaml (v4):** `h+` is another track. High `c+` =",
        "   arrived at the other song. Not this page.",
        "2. **Last-token transplant (uni-v2, same-room yaml):** student =",
        "   encode(neu tokens, LoRA @ +1), teacher last = encode(pos tokens).",
        "   Loss is last-hidden MSE only. The last real token is",
        "   `<|audio_start|>`. The LoRA still rewrites every prefix token,",
        "   including lyrics. Matching last hidden to `h+` does not match",
        "   the KV of the neu prefix. + REF (pos caption, no LoRA) still",
        "   sings the yaml line. That is this page.",
        "",
        "## 1. Existing metrics — which ones fire",
        "",
        "Last-hidden scoring of **every** existing caption metric misses",
        "the transplant: if last = `h+`, off-caption / garble /",
        "`same_words` / coherence look like a + caption hit. Last-hidden",
        "sheet `lyric_mass` is 0 on **both** cells (the + caption rollout",
        "is concept words), so it flags grit *and* gender and cannot",
        "split them.",
        "",
        "On the **prefix sung line**, grit UNI sings on-caption concept",
        f"words (`{ood['grit_sings_prefix']}`). Plus-exam off-caption,",
        "pair-exam `off_corpus` / `same_words` / coherence, and sheet",
        "garble stay green. Gender/tempo-like UNI keeps the yaml line",
        f"(`{ood['gender_sings_prefix']}`).",
        "",
        "The only existing column that flags grit shred and keeps gender",
        "is **sheet `lyric_mass` / continuation vs the yaml lyric sheet**,",
        "scored on the prefix sung line — not a new scale. Gate is the",
        f"existing pair-exam continuation floor `{EXAM_ROLL_OVERLAP:g}`.",
        "",
        "| metric | last-hidden grit | last-hidden gender | prefix grit | prefix gender | flags grit-not-gender? |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for name in EXISTING_OOD_METRICS:
        key = f"prefix_sung.{name}"
        lines.append(
            "| {label} | {lg} {flg} | {lgen} {flgen} | {pg} {fpg} | {pgen} {fpgen} | {use} |".format(
                label=METRIC_LABELS[name],
                lg=_f(grit_l["values"][name]),
                flg=_flag(grit_l["flags"][name]),
                lgen=_f(gender_l["values"][name]),
                flgen=_flag(gender_l["flags"][name]),
                pg=_f(grit_p["values"][name]),
                fpg=_flag(grit_p["flags"][name]),
                pgen=_f(gender_p["values"][name]),
                fpgen=_flag(gender_p["flags"][name]),
                use=_useful(key, useful),
            )
        )
    lines += [
        "",
        f"Useful (flags grit, not gender): `{', '.join(useful) or 'none'}`.",
        f"False alarm (flags gender keep): `{', '.join(ood['false_alarm']) or 'none'}`.",
        "",
        "![existing metrics on UNI grit vs gender](lm-lyric-recall/existing-ood.png)",
        "",
        "Live implication: a last-hidden off-caption / garble / `c+` board",
        "would have called grit UNI a hit. Whisper vs the yaml lyric sheet",
        "is the existing listen analog of prefix `lyric_mass`.",
        "",
        "## 2. `faithful_plus_neu` implementation bugs",
        "",
        "Formulation stays: MSE +1 last → raw `h+`, MSE 0 → `h0`, no minus,",
        "no leftover-gate, student = encode(neu)+LoRA. These are",
        "implementation mistakes that would cause OOD even if that math is",
        "right.",
        "",
        "| check | status |",
        "|---|---|",
        "| Teacher encoded before LoRA exists (`_encode_static` / `@torch.no_grad`) | ok |",
        "| Student tokens are `neu_ids`, not `pos_ids` | ok |",
        "| Teacher is raw `h+` (not leftover-gated) | ok |",
        "| Scale 0 sets LoRA multiplier 0 (identity) | ok |",
        "| LoRA wraps `Qwen3Attention` only (not `embed_tokens`) | ok |",
        "| `_assemble` ends with `{im_end}{audio_start}` | ok |",
        "| Last-hidden gather used **shape-1**, not the mask | **fixed** — now `_gather_last_hidden` / last-real index |",
        "| No assert last token is `<|audio_start|>` | **fixed** — fail closed when the tokenizer can say |",
        "| Plus+neu still teacher-forced scale **−1** endreg / planreg | **fixed** — minus pole skipped |",
        "| Default `early_stop` required `c-` / `nperc` / collapse | **fixed** — plus+neu uses `c+` / `p%` only |",
        "| `infer_music3` default prompt was yaml `target` (often +) | **fixed** — prefers `neutral`; warns on plus+neu sidecars |",
        "| `generate_listen` already uses yaml `neutral` + LoRA | ok; now prints the double-+ warning |",
        "",
        "Endreg at +1 still regularizes prompt-last + ~250 frames. That",
        "does not pin the lyric prefix KV, so it does not by itself cause",
        "the transplant — but backpropping minus-side end-margin on a",
        "no-minus card was a formulation leak.",
        "",
        "Default stays `--lm_target v9` / `--pole_mode hidden`. No v4",
        "rewrite. No GPU train on this branch.",
        "",
        "## 3. Prefix-hold (secondary, already wired)",
        "",
        "Opt-in `--lm_target faithful_plus_neu_prefix` holds the +1 prefix",
        "hidden to encode(neu). Cheap leftover from the previous pass.",
        "Not the point. UNI last-token MSE still sits in the old plus+neu",
        "want-box (cover / neu_hold / off-caption) while prefix",
        f"`lyric_mass` is `{_f(verdict['uni_lyric_recall'][0])}` on grit",
        f"and `{_f(verdict['uni_lyric_recall'][1])}` on close.",
        "",
        f"Prefix-hold lifts grit lyric-sheet mass: **{'yes' if verdict['prefix_lifts_lyric_recall'] else 'no'}**",
        f"({', '.join(_f(x) for x in verdict['prefix_lyric_recall'])}).",
        f"Keeps cover: **{'yes' if verdict['prefix_keeps_cover'] else 'no'}**.",
        "",
        "```bash",
        "CUDA_VISIBLE_DEVICES=N python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name energy-lm-uni-prefix \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
        "  --lm_target faithful_plus_neu_prefix --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0 --device 0",
        "```",
        "",
        "v4 yaml is not rewritten. Infer plus+neu with the **neutral**",
        "caption + LoRA, not the + caption.",
        "",
        "## 4. Lyric-token hold (one-recipe candidate)",
        "",
        "`--lm_target faithful_plus_neu` = last-token UNI (gender / tempo).",
        "`--lm_target faithful_plus_neu_prefix` = whole-prefix hold (grit /",
        "distortion / joy). `--lm_target faithful_plus_neu_lyric` holds only",
        "the yaml `lyrics` span so Vocal Details can still flip woman. Ranked",
        "on [lm-lyric-hold.md](lm-lyric-hold.md). Default stays",
        "`--lm_target v9` / `--pole_mode hidden`.",
        "",
        "## Related cells",
        "",
        "- [lm-lyric-hold.md](lm-lyric-hold.md) — grit lyrics vs gender_move scoreboard.",
        "- [lm-plus-neu-exam.md](lm-plus-neu-exam.md) — last-hidden cover / neu_hold / off-caption.",
        "- [lm-plus-exam.md](lm-plus-exam.md) — plus-only cover / off-caption.",
        "- [lm-pair-exam.md](lm-pair-exam.md) — bipolar continuation / same_words / off_corpus / coherence.",
        "- [lm-sheet-goodhart.md](lm-sheet-goodhart.md) — sheet on-sheet / garble / lyric_mass.",
        "- [lm-2d-scoreboard.md](lm-2d-scoreboard.md) — compiled bipolar board (not updated).",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_lyric_recall.py --out docs/lm-lyric-recall",
        "PYTHONPATH=. pytest tests/test_lm_lyric_recall.py tests/test_lm_plus_neu_exam.py tests/test_lm_trainer_v9.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights. Seed `0`, `400` Adam steps.",
        "",
    ]
    _ = (table, ranked, PLUS_COVER_MIN, PLUS_NEU_HOLD_MIN, PLUS_OFF_MAX, GARBLE_MAX)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table = lyric_exam_table(steps=args.steps, seed=args.seed)
    verdict = lyric_verdict(table)
    ranked = lyric_rank(table)
    ood = verdict["existing_ood"] or existing_ood_verdict(table)
    blob = {
        "scale": "existing-metric OOD + faithful_plus_neu bug hunt",
        "not_a_new_leaderboard": True,
        "not_the_bipolar_board": True,
        "scored": list(EXISTING_OOD_METRICS),
        "gates": {
            "plus_off_caption_max": PLUS_OFF_MAX,
            "pair_off_corpus_max": EXAM_ROLL_OFF_MAX,
            "pair_same_words_min": EXAM_MATCH_KEPT,
            "pair_coherence_min": EXAM_COHERENCE,
            "sheet_garble_max": GARBLE_MAX,
            "sheet_lyric_mass_min": EXAM_ROLL_OVERLAP,
        },
        "recipes": [c["name"] for c in LYRIC_RECIPES],
        "cells": list(LYRIC_CELLS),
        "steps": args.steps,
        "seed": args.seed,
        "existing_ood": ood,
        "verdict": {k: v for k, v in verdict.items() if k not in {"last_hidden_blind", "existing_ood"}},
        "last_hidden_blind": verdict["last_hidden_blind"],
        "rank_secondary": ranked,
        "rows": table,
    }
    (args.out / "metrics.json").write_text(
        json.dumps(blob, indent=2, default=str) + "\n", encoding="utf-8"
    )
    plot_existing_ood(ood, args.out / "existing-ood.png")
    write_markdown(table, verdict, ranked, ood, _REPO / "docs" / "lm-lyric-recall.md")
    print(
        f"wrote {args.out}  useful={ood['useful']} "
        f"false_alarm={ood['false_alarm']} "
        f"only_prefix_lyric_sheet={ood['only_prefix_lyric_sheet']}"
    )


if __name__ == "__main__":
    main()
