#!/usr/bin/env python3
"""Compile every scored 2-D / high-D / sheet recipe into one gated table."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.exam import LIVE_EXAM
from analysis.slider2d.scoreboard import (
    CELL_LABEL,
    CELL_ORDER,
    FAILS,
    UNSCORED,
    WORKS,
    WORKS_SOME,
    collect_scoreboard,
    floatable_row,
    gates_blob,
    live_exam_report,
    sort_rows,
)


DEFAULT_OUT = _REPO / "docs" / "lm-2d-scoreboard"


def _fmt(value, spec: str, empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _verdict_md(verdict: str) -> str:
    if verdict == WORKS:
        return "**works**"
    if verdict == WORKS_SOME:
        return "works-on-some-pairs"
    if verdict == UNSCORED:
        return "unscored"
    return "**fails**"


CELL_MARK = {True: "pass", False: "**fail**", None: "—"}


PAIRS_HEADER = (
    "| recipe | exam_score | " + " | ".join(c.replace("exam_", "") for c in CELL_ORDER)
    + " | predicts live | compiled |\n"
    "|---|---:|" + "---|" * len(CELL_ORDER) + "---|---|"
)


def _pairs_md(row: dict) -> str:
    cells = " | ".join(CELL_MARK[row["cells"].get(name)] for name in CELL_ORDER)
    runs = row.get("predicts") or {}
    named = ", ".join(f"`{run}` ({cell.replace('exam_', '')})" for cell, run in runs.items())
    return (
        f"| `{row['id']}` | {_fmt(row.get('exam_score'), '.3f')} | {cells} | "
        f"{named or '—'} | {_verdict_md(row['compiled'])} |"
    )


TABLE_HEADER = (
    "| recipe | exam_score | leftover leak | on-sheet | kept | off-sheet | argmax | "
    "swing | pair-odd cos *(log)* | ±1 *(log)* | intended cos | "
    "c+ | perc | rich-kept | compiled |\n"
    "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|"
)


def _table_md(row: dict) -> str:
    return (
        f"| `{row['id']}` | {_fmt(row.get('exam_score'), '.3f')} | "
        f"{_fmt(row['leftover_leak'], '+.3f')} | "
        f"{_fmt(row['on_sheet'], '.3f')} | {_fmt(row['on_sheet_kept'], '.3f')} | "
        f"{_fmt(row['off_sheet'], '.3f')} | {_fmt(row['argmax_on_sheet'], '.2f')} | "
        f"{_fmt(row['swing_kept'], '.2f')} | {_fmt(row['pair_odd_cos'], '+.3f')} | "
        f"{_fmt(row['collapse'], '+.3f')} | {_fmt(row['intended_cos'], '+.3f')} | "
        f"{_fmt(row['trainer_c_plus'], '+.3f')} | {_fmt(row['perc'], '.0f')} | "
        f"{_fmt(row['rich_kept'], '.2f')} | {_verdict_md(row['compiled'])} |"
    )


def plot_scoreboard(rows: list[dict], path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8.4, 5.2))
    colors = {
        WORKS: "#1e8449",
        WORKS_SOME: "#b9770e",
        FAILS: "#c0392b",
        UNSCORED: "#7f8c8d",
    }
    for verdict, color in colors.items():
        pts = [r for r in rows if r["compiled"] == verdict]
        xs = [0.0 if r["leftover_leak"] is None else r["leftover_leak"] for r in pts]
        ys = [0.0 if r["on_sheet_kept"] is None else r["on_sheet_kept"] for r in pts]
        ax.scatter(xs, ys, c=color, s=42, label=verdict, zorder=3)
        for row, x, y in zip(pts, xs, ys):
            ax.annotate(row["id"], (x, y), fontsize=6.4, xytext=(4, 3), textcoords="offset points")
    ax.axvline(0.20, color="#7f8c8d", ls=":", lw=0.9)
    ax.axhline(0.90, color="#7f8c8d", ls=":", lw=0.9)
    ax.set_xlabel("leftover leak  (unused mix / BPM / gender)")
    ax.set_ylabel("on-sheet kept  (N/A plotted at 0)")
    ax.set_title("compiled gate: leak small and, when a sheet exists, stay on it")
    ax.grid(alpha=0.25)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_report(rows: list[dict], blob: dict, path: Path) -> None:
    gates = blob["gates"]
    live = blob["live_exam"]
    winners = [r for r in rows if r["compiled"] == WORKS]
    gender_only = [r for r in rows if r["compiled"] == WORKS_SOME]
    fails = [r for r in rows if r["compiled"] == FAILS]
    agree = sum(1 for r in live if r["agrees"])
    lines = [
        "# 2-D / high-D / sheet / pair-exam scoreboard",
        "",
        "Generated by `analysis/slider2d/run_lm_scoreboard.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default.",
        "",
        "Every other cell in this repo scores one question. This page joins",
        "those real fixture numbers into one table and applies one gate. It",
        "does not invent a loss.",
        "",
        "## The exam this board is graded on",
        "",
        "Three live Music 3 runs, 2026-08-25, after the #24 wire. rank 8 /",
        "alpha 8 / lr 5e-4 / 800 steps / seed 7 / `--no-early_stop` / endreg 1.0",
        "/ hold 0, pair-odd early-stop gates deliberately off.",
        "",
        "| live run | recipe | prompts | c+ | ±1 | p% / n% | loss | ears |",
        "|---|---|---|---:|---:|---:|---:|---|",
    ]
    for run, info in LIVE_EXAM.items():
        lines.append(
            f"| `{run}` | `--lm_target {info['teacher']} --pole_mode "
            f"{info['pole_mode']}` | `{info['prompts']}` | {info['c_plus']:+.3f} | "
            f"{info['collapse']:+.3f} | {info['pperc']:.2f} / {info['nperc']:.2f} | "
            f"{info['loss']:.4f} | "
            f"{'PASS' if info['listen'] == 'pass' else 'FAIL'} — {info['heard']} |"
        )
    lines += [
        "",
        "Two of those are the **same recipe** on different prompt files, and",
        "the one with the smallest loss, the best `c+` and the lowest `p%` is",
        "one of the two that garbled. So a recipe is not one row: it is a",
        "**recipe × pair** grid. The sortable number is `exam_score` =",
        "`min(overlap, swing)` over the live exam pairs that row is read on.",
        "",
        f"| live run | fixture row | pair | predicted | ears | agrees | why |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in live:
        lines.append(
            f"| `{row['run']}` | `{row['recipe']}` | `{row['cell']}` | "
            f"**{row['predicted'].upper()}** | **{row['listen'].upper()}** | "
            f"{'yes' if row['agrees'] else 'NO'} | {row['reason']} |"
        )
    lines += [
        "",
        f"{agree} of {len(live)} agree. Full derivation, sweeps and caveats in",
        "[lm-pair-exam.md](lm-pair-exam.md).",
        "",
        "## The compiled gate",
        "",
        gates["prose"],
        "",
        "Pair-exam cells, on what the student sings over its own 8-token",
        "continuation:",
        "",
        f"- continuation overlap with the pole's words: `≥ {gates['exam_overlap']}`",
        f"- position-wise agreement / the pole's own cross-draw agreement: `≥ {gates['exam_match_kept']}`",
        f"- off-caption mass: `≤ {gates['exam_off_caption']}`",
        f"- coherence, consecutive words from the same song: `≥ {gates['exam_coherence']}`",
        f"- audible swing kept: `≥ {gates['exam_swing']}`",
        "",
        "#22 sheet cells, on the one token at `<|audio_start|>`:",
        "",
        f"- leftover leak lock: `{gates['leak_lock']}`",
        f"- on-sheet kept: `≥ {gates['sheet_lock']}`",
        f"- off-sheet mass: `≤ {gates['garble_max']}`",
        f"- argmax-on-sheet: `{gates['argmax_lock']:g}`",
        f"- concept swing kept: `≥ {gates['swing_floor']}`",
        "",
        "Never an input to any gate:",
        "",
        f"- pair-odd cos scored: `{gates['pair_odd_cos_scored']}`",
        f"- ±1 collapse scored: `{gates['collapse_scored']}`",
        f"- pole loss scored: `{gates['pole_loss_scored']}`",
        f"- p% / n% scored: `{gates['perc_scored']}`",
        "",
        "A missing cell is `—`, not a free pass. On the sheet cells a missing",
        "sheet column is not a free pass for a midpoint teacher either: those",
        "rows inherit the leftover sheet of `t± = h0 ± a`, because deleting",
        "`c` is a fact about the target point, not about the hidden width.",
        "",
        "## Which pairs each recipe passes",
        "",
        "Sorted by `exam_score` descending, nulls last. `exam_score` is",
        "`min(overlap, swing)` on `exam_divergent` (energy-v4) and",
        "`exam_close` (gender-v4) only — unused_e and the sheet cells are",
        "other questions. A pair with no reading is skipped, not a free 1.0.",
        "The verdict stays a label; the number is what a human sorts by.",
        "",
        PAIRS_HEADER,
    ]
    lines += [_pairs_md(r) for r in rows]
    lines += [
        "",
        "What each cell is:",
        "",
    ]
    lines += [f"- `{name.replace('exam_', '')}` — {CELL_LABEL[name]}" for name in CELL_ORDER]
    lines += [
        "",
        "The two `semantic_kl_poles` cells are the load-bearing row: it is the",
        "live energy win on a divergent pair and the live gender garble on a",
        "close one, so no single verdict for the recipe is honest and",
        "`works-on-some-pairs` names which.",
        "",
        "## Two new techniques, and what they change",
        "",
        "`faithful_guard_e` and the `dual_band` rows are new here. Full",
        "derivation, the 2×2 ablation and the seed spread are in",
        "[lm-pair-exam.md](lm-pair-exam.md#two-techniques-that-top-both-pairs).",
        "",
        "**The blend guard** (`lm_blend_guard`, `--lm_target faithful_guard_e`)",
        "is a threshold-free admissibility test on a target point: it is",
        "admissible while it is nearer the pole caption it claims to be than",
        "the pair's own midpoint. Subtracting a declared `ê_⊥` is taken only",
        "when it passes. On energy-v4 it does not — the yaml's `ê` restates the",
        "genre and BPM the poles move, the ê-cleaned target lands 0.78‖a‖ from",
        "its caption and 0.63‖a‖ from the midpoint, and the guard keeps the",
        "caption instead. On a pair whose `ê` really is a leftover it is taken",
        "and the leak goes to 0.000. That is one recipe for both pair types,",
        "and it is the only row on this board that passes every cell without",
        "rewriting a caption.",
        "",
        "**The dual-band loss** (`lm_dual_band_pole_loss`, `--pole_mode",
        "dual_band`) keeps the live v16 semantic KL where the head reads and",
        "adds hidden MSE on the band it is blind to, which is where a close",
        "pair's axis lives and where a KL's gradient is exactly zero. It is the",
        "smallest change to the recipe that garbled `gender-lm-v16`: same",
        "target, one added term, and the close pair's swing goes from 0.387 to",
        "0.994 while the divergent pair is untouched.",
        "",
        "`dual_band_midpoint` is on the board as the control. It pins the blind",
        "band and still fails the divergent pair, which is what says the target",
        "point has to be a real caption and the loss alone is not the fix.",
        "",
        "## Short verdict",
        "",
    ]
    if winners:
        names = ", ".join(f"`{r['id']}`" for r in winners)
        lines.append(
            f"**Works on every pair it is read on:** {names}. "
            "`faithful_guard_e` is the new one and the only one that gets "
            "there from the yamls as written: `--lm_target faithful_guard_e "
            "--pole_mode hidden`, blend-guarded ê on real poles. "
            "`faithful_attrs` is `--lm_target faithful --pole_mode hidden` plus "
            "a data fix — the unpinned attribute written into both pole "
            "captions, the way energy-v4 already pins the singer with "
            "`attributes` — so there is no leftover ê in the text for the "
            "sheet cell to charge it for. `dual_band_guard_e` is both new "
            "pieces at once and passes every cell too, at a slightly lower "
            "exam_score than hidden MSE reaches."
        )
    else:
        lines.append("No recipe passed on every pair it is read on.")
    if gender_only:
        names = ", ".join(f"`{r['id']}`" for r in gender_only)
        lines += [
            "",
            f"**Works on some pairs:** {names}. Each passes at least one pair "
            "and fails another. `faithful_raw` (and `hidden_beta1`, which is "
            "the same target reached through `--lm_target symmetric "
            "--common_beta 1`) passes all three pair cells and is charged only "
            "by the unused-ê sheet — which is the cell `faithful_guard_e` "
            "fixes by deciding, per pair, whether the declared ê is safe to "
            "subtract. `dual_band_poles` is charged by the same leak for the "
            "same reason: it is a loss, and a loss does not clean a target. "
            "`semantic_kl_poles` is the row the live exam is about: the energy "
            "win and the gender garble.",
        ]
    lines += [
        "",
        f"**Fails:** {len(fails)} recipes — hub, hold-ê raw, short-û and rich-û "
        "project, and the high-D leftover holds. None of them has a pair-exam "
        "reading; they fail on leftover leak and the sheet alone. A perfect "
        "pair-odd lock and a solved pole loss are both failure modes here.",
        "",
        "One caveat on the number itself: `exam_score` is a seed-0 reading of a "
        "sampled rollout, and the top of the board is a band. Over four seeds "
        "`faithful_raw` and `faithful_guard_e` both range 0.994 … 1.000 and "
        "`dual_band_poles` 0.970 … 0.994, and all three pass both pairs at "
        "every seed. Sort on the number; do not subtract two of them.",
        "",
        "## The full joined table",
        "",
        "Every column the older cells contribute, in `exam_score` order.",
        "Pair-odd cos and ±1 are **logged, never scored**.",
        "",
        TABLE_HEADER,
    ]
    lines += [_table_md(r) for r in rows]
    lines += [
        "",
        "![leak vs on-sheet kept](lm-2d-scoreboard/scoreboard.png)",
        "",
        "## What each row is",
        "",
    ]
    for row in rows:
        extra = []
        if row.get("content_cos") is not None:
            extra.append(f"content-cos {_fmt(row['content_cos'], '+.3f')}")
        if row.get("polarity_distinct") is not None:
            extra.append(f"polarity {_fmt(row['polarity_distinct'], '+.3f')}")
        if row.get("trainer_c_plus_distinct") is not None:
            extra.append(f"c+ distinct {_fmt(row['trainer_c_plus_distinct'], '+.3f')}")
        if row.get("loss") is not None:
            extra.append(f"loss {_fmt(row['loss'], '.3f')}")
        suffix = f" ({'; '.join(extra)})" if extra else ""
        lines.append(
            f"- `{row['id']}` — {row['label']}. {row['notes']} "
            f"Fixture: {row['fixture']}.{suffix}"
        )
        for cell, reason in (row.get("exam_reason") or {}).items():
            run = (row.get("predicts") or {}).get(cell)
            live = f" — live `{run}`" if run else ""
            lines.append(
                f"  - {cell.replace('exam_', '')} pair{live}: {reason}"
            )
    lines += [
        "",
        "## The next live cards the board points at",
        "",
        "`faithful_raw` — `--lm_target faithful --pole_mode hidden` — is still",
        "the untrained winner on the two live pairs, and the card #28 already",
        "pointed at. It is the one recipe that fixes what `gender-lm-v16`",
        "actually did wrong. Both aim at the same target — the real pole",
        "captions — so the target point is not the difference. The difference",
        "is that hidden MSE pins the whole state, including the part of it the",
        "semantic band does not read at `<|audio_start|>`, which on a close pair",
        "is where the axis lives. In the pair-exam cell that recipe copies 1.00",
        "of the invisible block against semantic KL's 0.00, and it is the swing",
        "over the continuation that separates them, not the loss.",
        "",
        "```bash",
        "python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name gender-lm-v19 \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-gender-v4.yaml \\",
        "  --lm_target faithful --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0",
        "```",
        "",
        "gender-v4 declares no `leak_*`, so hold is 0 and the sheet cell's",
        "leftover-leak charge against `faithful` does not apply to this yaml.",
        "What to watch: `p%` / `n%` should land near the shipped v9 residual",
        "(~5%) instead of `gender-lm-v16`'s 0.523 / 0.777. `c+` will print",
        "*worse* than v9's and the ±1 collapse will sit near the logged pair",
        "cos rather than −1; per #22 and this board that is expected under a",
        "caption target and is not a regression. The listen is the gate.",
        "",
        "The new row the board adds is the *energy* card, on the yaml that has",
        "a `leak_*` pair and where every previous attempt to use it deleted the",
        "slider. `faithful_guard_e` reads that yaml as written and refuses the",
        "subtraction, so it should sound like `energy-lm-v18` (the win) rather",
        "than `energy-lm-v16` (the garble), and it needs no second recipe name",
        "for the gender pair.",
        "",
        "```bash",
        "python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name energy-lm-v20 \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
        "  --lm_target faithful_guard_e --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0",
        "```",
        "",
        "What to watch: the per-row setup line prints `guard=REFUSED (poles)`",
        "with `to_pole` / `to_mid` next to it. If it prints `guard=sub_e` on",
        "energy-v4 then the live pair geometry is not this fixture's and the",
        "board is wrong about that yaml — which is the cheap falsification, and",
        "it costs one setup pass rather than 800 steps. The same flag on",
        "gender-v4 prints `guard=no-ê` and is `faithful` exactly.",
        "",
        "`--pole_mode dual_band` is the card for anyone who wants to keep the",
        "v16 semantic KL: same `--lm_target faithful`, one added term, and the",
        "run prints how many blind dims it found. If it prints 0 the semantic",
        "band's row space fills the hidden width and the mode is plain",
        "`semantic_kl` — raise `--blind_cut` before reading anything into it.",
        "",
        "None of this changes the live default, which is still `--lm_target v9`",
        "/ `--pole_mode hidden`.",
        "",
        "## Why four columns are logged and never scored",
        "",
        "**Pair-odd cos and the ±1 collapse** (#22). On the leftover sheet",
        "`v9_hidden` prints `cos(d+, a) = +1.000` and `cos(d+, d−) = −1.000`",
        "while keeping about a third of the caption's on-sheet mass.",
        "",
        "**The pole loss and p% / n%** (2026-08-25). `gender-lm-v16` printed",
        "the campaign's smallest pole loss (0.0091) with `p% / n% = 0.523 /",
        "0.777` on the same step, and its lyrics came out garbled. A semantic-KL",
        "loss has zero gradient on the part of the hidden state the semantic",
        "band does not read, so on a close pair it reaches its floor without",
        "the axis arriving at all: the loss cannot distinguish \"solved\" from",
        "\"there was nothing here I could see\".",
        "",
        "That is why the ordering rule is the pair, and why the previous",
        "version of this board ranked `semantic_kl_sub_e` (live",
        "`energy-lm-v16`, garbled) above `semantic_kl_poles` (live",
        "`energy-lm-v18`, the win): it scored the energy recipes on a",
        "same-song field with an unpinned attribute, which is not what",
        "energy-v4 is. That cell is still here and still the place leak is",
        "scored — it is no longer the energy stand-in.",
        "",
        "## Related cells",
        "",
        "- [lm-pair-exam.md](lm-pair-exam.md) — the pair cells, the rollout,",
        "  the divergence and visible-share sweeps, and the live exam.",
        "- [lm-sheet-goodhart.md](lm-sheet-goodhart.md) — the sheet readout",
        "  and the four locked recipes.",
        "- [lm-live-cells.md](lm-live-cells.md) — gender-like vs energy-like",
        "  hidden leak.",
        "- [lm-highd-leftover.md](lm-highd-leftover.md) — leftover ê, λ·D/2,",
        "  trainer c+.",
        "- [lm-rich-2d.md](lm-rich-2d.md) — project short û vs rich û.",
        "- [lm-faithful-2d.md](lm-faithful-2d.md) — raw poles vs attributes.",
        "- [lm-hold-overlap.md](lm-hold-overlap.md) — hold-ê raw vs ê_⊥û.",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_scoreboard.py --out docs/lm-2d-scoreboard",
        "PYTHONPATH=. pytest tests/test_lm_2d_scoreboard.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights.",
        "",
        f"Sheet seed `{blob['seed']}`, `{blob['sheet_steps']}` Adam steps; "
        f"pair-exam `{blob['exam_steps']}` steps, 8-token rollout, 4 draws; "
        f"other fixtures `{blob['other_steps']}` steps.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--sheet-steps", type=int, default=400)
    parser.add_argument("--other-steps", type=int, default=200)
    parser.add_argument("--exam-steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)

    out = args.out
    out.mkdir(parents=True, exist_ok=True)
    rows = collect_scoreboard(
        sheet_steps=args.sheet_steps,
        other_steps=args.other_steps,
        exam_steps=args.exam_steps,
        seed=args.seed,
    )
    rows = sort_rows(rows)
    live = live_exam_report(exam_steps=args.exam_steps, seed=args.seed)
    blob = {
        "sheet_steps": args.sheet_steps,
        "other_steps": args.other_steps,
        "exam_steps": args.exam_steps,
        "seed": args.seed,
        "gates": gates_blob(),
        "cells": list(CELL_ORDER),
        "live_exam": [
            {k: v for k, v in row.items() if k != "row"} for row in live
        ],
        "rows": [floatable_row(r) for r in rows],
        "live_default_unchanged": True,
    }
    (out / "metrics.json").write_text(json.dumps(blob, indent=2) + "\n", encoding="utf-8")
    plot_scoreboard(rows, out / "scoreboard.png")
    write_report(rows, blob, out.parent / "lm-2d-scoreboard.md")
    for row in rows:
        cells = "".join(
            {True: "P", False: "F", None: "-"}[row["cells"].get(name)]
            for name in CELL_ORDER
        )
        print(
            f"{row['compiled']:20s} {row['id']:26s} "
            f"exam={_fmt(row.get('exam_score'), '.3f')} {cells} "
            f"leak={_fmt(row['leftover_leak'], '+.3f')} "
            f"cos={_fmt(row['pair_odd_cos'], '+.3f')}"
        )
    for row in live:
        print(
            f"{'live':20s} {row['run']:26s} {row['cell']:10s} "
            f"predicted={row['predicted']:5s} ears={row['listen']:5s} "
            f"agrees={row['agrees']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
