#!/usr/bin/env python3
"""Role-split UNI 2D scoreboard: grit lyrics vs gender_move."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.lyric_recall import LYRIC_RECALL_MIN
from analysis.slider2d.plus_exam import PLUS_COVER_MIN
from analysis.slider2d.plus_neu_exam import PLUS_NEU_HOLD_MIN
from analysis.slider2d.roles import (
    GENDER_MOVE_MIN,
    ROLE_CELLS,
    ROLE_RECIPES,
    role_exam_table,
    role_rank,
    role_verdict,
)


DEFAULT_OUT = _REPO / "docs" / "lm-roles"

COLORS = {
    "faithful_plus_neu": "#7d3c98",
    "faithful_plus_neu_prefix": "#2471a3",
    "faithful_plus_neu_roles": "#1e8449",
}
MARKS = {"divergent": "o", "close": "s"}


def _f(value, spec: str = ".3f", empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _hit(flag: bool) -> str:
    return "**HIT**" if flag else "miss"


def plot_roles_board(table: dict[str, list[dict]], path: Path) -> None:
    """lyric_recall vs gender_move. Want-box is high both."""
    fig, ax = plt.subplots(figsize=(8.8, 5.8))
    want = Rectangle(
        (LYRIC_RECALL_MIN, GENDER_MOVE_MIN),
        1.0 - LYRIC_RECALL_MIN,
        1.0 - GENDER_MOVE_MIN,
        facecolor="#d5f5e3",
        edgecolor="#1e8449",
        lw=1.0,
        alpha=0.55,
        zorder=1,
        label="want-box (grit lyric HIT and gender_move HIT)",
    )
    ax.add_patch(want)
    for cell, rows in table.items():
        for row in rows:
            ax.scatter(
                [row["lyric_recall"]],
                [row["gender_move"]],
                c=[COLORS[row["name"]]],
                marker=MARKS.get(cell, "o"),
                s=120,
                zorder=3,
                edgecolors="black",
                linewidths=0.6,
            )
    ax.axvline(LYRIC_RECALL_MIN, color="#1e8449", ls=":", lw=0.8)
    ax.axhline(GENDER_MOVE_MIN, color="#1e8449", ls=":", lw=0.8)
    ax.set_xlim(-0.05, 1.05)
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("lyric_recall @ +1  (grit fail = punk punk)")
    ax.set_ylabel("gender_move  (Vocal Details at +1 vs neu)")
    ax.set_title(
        "Role-split UNI — both pair types on one board\n"
        "circle = grit-like / divergent    square = gender-like / close"
    )
    ax.grid(alpha=0.25)
    handles = [
        plt.Line2D(
            [0],
            [0],
            marker="o",
            color="none",
            markerfacecolor=COLORS[name],
            markeredgecolor="black",
            markersize=9,
            label=name,
        )
        for name in COLORS
    ]
    handles.append(want)
    ax.legend(handles=handles, fontsize=8, loc="lower left")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_markdown(
    table: dict[str, list[dict]],
    verdict: dict,
    ranked: list[dict],
    path: Path,
) -> None:
    by = {cell: {r["name"]: r for r in rows} for cell, rows in table.items()}
    want = "HIT" if verdict["want_box"] else "miss"
    lines = [
        "# Role-split UNI: lyrics stay, Vocal Details may move",
        "",
        "Generated by `analysis/slider2d/run_lm_roles.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default",
        "(`--lm_target v9` / `--pole_mode hidden`). Third UNI family: not",
        "whole-prefix hold, not lyric-token hold-to-neu, not last-delta",
        "projected off the lyric span.",
        "",
        "Two failures on one board:",
        "",
        "1. **Grit-like / divergent** — last-token UNI transplants the",
        "   prefix KV. Sung line becomes `punk punk` instead of the yaml",
        "   lyric. Fail = `lyric_recall@+1` below 0.85.",
        "2. **Gender-like / close** — whole-prefix hold pins Vocal Details",
        "   to ungendered neu, so woman cannot move on a neu listen.",
        "   Fail = `gender_move` below 0.85 (Vocal Details at +1 still",
        "   equals encode(neu)).",
        "",
        f"**Want-box: grit lyric HIT and gender_move HIT → `{want}`**",
        "",
        "![lyric_recall vs gender_move](lm-roles/roles-board.png)",
        "",
        "## How spans are found",
        "",
        "Assembled prompt is",
        "`<|im_start|><|caption_start|>…<|caption_end|><|lyrics_start|>…`",
        "`<|lyrics_end|><|im_end|><|audio_start|>`. The tokenizer can",
        "locate those special tokens as unique ids.",
        "",
        "- **Lyrics** — exclusive span between `<|lyrics_start|>` and",
        "  `<|lyrics_end|>`. Same yaml line on neu and pos, so token-wise",
        "  MSE is aligned. Fail closed if empty.",
        "- **Concept** — prefer Vocal Details: after the `Vocal Details:`",
        "  heading, until `Arrangement:` or `<|caption_end|>`. Woman lives",
        "  here on gender-v4. If that heading is not a unique token run,",
        "  fall back to the exclusive caption span. Fail closed if empty.",
        "- **Last** — must be `<|audio_start|>`. Fail closed when the",
        "  tokenizer can say.",
        "",
        "Pos Vocal Details is longer than neu on gender-v4 (extra woman",
        "text), so concept MSE is pooled when lengths differ. Lyrics stay",
        "token-wise. No minus teacher, no leftover-gate.",
        "",
        "Why not only Vocal Details taught and everything else lyric-held?",
        "The heading search can miss (BPE of `Vocal Details:` is not a",
        "special token). The caption special-token span is the split the",
        "tokenizer can always locate. When the heading is found, concept",
        "narrows to Vocal Details; Global Metadata / Arrangement are then",
        "unconstrained (shared LoRA only).",
        "",
        "## Train card (opt-in)",
        "",
        "`--lm_target faithful_plus_neu_roles --pole_mode hidden`. Teacher",
        "is raw `h+` at last. +1 lyrics → encode(neu). +1 Vocal Details /",
        "caption → encode(pos). Scale 0 → `h0`.",
        "",
        "```bash",
        "CUDA_VISIBLE_DEVICES=N python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name energy-lm-uni-roles \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
        "  --lm_target faithful_plus_neu_roles --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0 --device 0",
        "```",
        "",
        "Default stays `--lm_target v9` / `--pole_mode hidden`.",
        "`faithful_plus_neu` and `faithful_plus_neu_prefix` are unchanged.",
        "",
        "## Rank (lyric_recall, cover, neu_hold, gender_move)",
        "",
        "| rank | recipe | in want-box | lyric_recall | cover | neu_hold | gender_move | grit lyric | gender_move (close) |",
        "|---:|---|---|---:|---:|---:|---:|---|---|",
    ]
    for row in ranked:
        lines.append(
            "| {rank} | `{name}` | {box} | {lr} | {cv} | {nh} | {gm} | {gl} | {gh} |".format(
                rank=row["rank"],
                name=row["name"],
                box="**yes**" if row["in_box"] else "no",
                lr=_f(row["lyric_recall"]),
                cv=_f(row["cover"]),
                nh=_f(row["neu_hold"]),
                gm=_f(row["gender_move"]),
                gl=_hit(bool(row["lyric_hit_divergent"])),
                gh=_hit(bool(row["gender_hit_close"])),
            )
        )
    lines += [
        "",
        "## Per-cell rows",
        "",
    ]
    for cell in ("divergent", "close"):
        label = "grit-like / divergent" if cell == "divergent" else "gender-like / close"
        lines += [
            f"### {label}",
            "",
            "| recipe | lyric_recall | cover | neu_hold | gender_move | sings lyrics | sings Vocal Details |",
            "|---|---:|---:|---:|---:|---|---|",
        ]
        for name in [c["name"] for c in ROLE_RECIPES]:
            row = by[cell][name]
            lines.append(
                "| `{name}` | {lr} | {cv} | {nh} | {gm} | `{ly}` | `{vd}` |".format(
                    name=name,
                    lr=_f(row["lyric_recall"]),
                    cv=_f(row["cover"]),
                    nh=_f(row["neu_hold"]),
                    gm=_f(row["gender_move"]),
                    ly=row["sings_lyric"],
                    vd=row["sings_concept"],
                )
            )
        lines.append("")
    lines += [
        "## Verdict",
        "",
        f"- last-token UNI grit lyric: {_hit(verdict['uni_grit_lyric'])} "
        f"(`{verdict['uni_sings_lyric_divergent']}`)",
        f"- whole-prefix hold gender_move: {_hit(verdict['prefix_gender_move'])} "
        f"(close VD `{verdict['prefix_sings_concept_close']}`)",
        f"- role-split grit lyric: {_hit(verdict['roles_grit_lyric'])} "
        f"(`{verdict['roles_sings_lyric_divergent']}`)",
        f"- role-split gender_move: {_hit(verdict['roles_gender_move'])} "
        f"(close VD `{verdict['roles_sings_concept_close']}`)",
        f"- want-box: **{want}**",
        "",
        "Not scored: `exam_score`, `leak_frac`, `c+`, `p%`.",
        "",
        "## Related cells",
        "",
        "- [lm-lyric-recall.md](lm-lyric-recall.md) — existing-metric OOD + last-token transplant.",
        "- [lm-plus-neu-exam.md](lm-plus-neu-exam.md) — last-hidden cover / neu_hold / off-caption.",
        "- [lm-plus-exam.md](lm-plus-exam.md) — plus-only cover / off-caption.",
        "- [lm-2d-scoreboard.md](lm-2d-scoreboard.md) — compiled bipolar board (not updated).",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_roles.py --out docs/lm-roles",
        "PYTHONPATH=. pytest tests/test_lm_roles.py tests/test_lm_lyric_recall.py tests/test_lm_plus_neu_exam.py tests/test_lm_trainer_v9.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights. Seed `0`, `400` Adam steps.",
        "",
    ]
    _ = (PLUS_COVER_MIN, PLUS_NEU_HOLD_MIN)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table = role_exam_table(steps=args.steps, seed=args.seed)
    verdict = role_verdict(table)
    ranked = role_rank(table)
    blob = {
        "scale": "role-split UNI: lyric_recall vs gender_move",
        "flag": "faithful_plus_neu_roles",
        "not_the_bipolar_board": True,
        "scored": ["lyric_recall", "cover", "neu_hold", "gender_move"],
        "gates": {
            "lyric_recall_min": LYRIC_RECALL_MIN,
            "cover_min": PLUS_COVER_MIN,
            "neu_hold_min": PLUS_NEU_HOLD_MIN,
            "gender_move_min": GENDER_MOVE_MIN,
        },
        "recipes": [c["name"] for c in ROLE_RECIPES],
        "cells": list(ROLE_CELLS),
        "steps": args.steps,
        "seed": args.seed,
        "verdict": verdict,
        "rank": ranked,
        "rows": table,
    }
    (args.out / "metrics.json").write_text(
        json.dumps(blob, indent=2, default=str) + "\n", encoding="utf-8"
    )
    plot_roles_board(table, args.out / "roles-board.png")
    write_markdown(table, verdict, ranked, _REPO / "docs" / "lm-roles.md")
    print(
        f"wrote {args.out}  want_box={verdict['want_box']} "
        f"roles_grit_lyric={verdict['roles_grit_lyric']} "
        f"roles_gender_move={verdict['roles_gender_move']}"
    )


if __name__ == "__main__":
    main()
