#!/usr/bin/env python3
"""Lyric-token UNI scoreboard: grit lyrics vs gender Vocal Details."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.exam import EXAM_ROLL_OVERLAP
from analysis.slider2d.lyric_recall import (
    GENDER_MOVE_MIN,
    LYRIC_CELLS,
    LYRIC_RECALL_MIN,
    LYRIC_RECIPES,
    lyric_exam_table,
    lyric_rank,
    lyric_verdict,
)
from analysis.slider2d.plus_exam import PLUS_COVER_MIN
from analysis.slider2d.plus_neu_exam import PLUS_NEU_HOLD_MIN


DEFAULT_OUT = _REPO / "docs" / "lm-lyric-hold"

COLORS = {
    "faithful_plus_neu": "#7d3c98",
    "faithful_plus_neu_prefix": "#2471a3",
    "faithful_plus_neu_lyric": "#1e8449",
    "faithful_plus": "#b9770e",
    "leftover_gate_bipolar": "#6c3483",
    "pair_odd_midpoint": "#c0392b",
}


def _f(value, spec: str = ".3f", empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _yn(flag: bool) -> str:
    return "**HIT**" if flag else "MISS"


def plot_want_box(ranked: list[dict], table: dict[str, list[dict]], path: Path) -> None:
    """Grit lyric_recall vs gender_move. Want-box is high both."""
    fig, ax = plt.subplots(figsize=(8.8, 5.8))
    want = Rectangle(
        (LYRIC_RECALL_MIN, GENDER_MOVE_MIN),
        1.0 - LYRIC_RECALL_MIN,
        1.0 - GENDER_MOVE_MIN,
        facecolor="#d5f5e3",
        edgecolor="#1e8449",
        lw=1.0,
        alpha=0.55,
        zorder=1,
        label="want-box (grit lyrics AND gender_move)",
    )
    ax.add_patch(want)
    by = {cell: {r["name"]: r for r in rows} for cell, rows in table.items()}
    for row in ranked:
        name = row["name"]
        grit = by["divergent"][name]["lyric_recall"]
        gender = by["close"][name]["gender_move"]
        cover = 0.5 * (by["divergent"][name]["cover"] + by["close"][name]["cover"])
        ax.scatter(
            [grit],
            [gender],
            s=90 + 160 * cover,
            c=COLORS.get(name, "#7f8c8d"),
            zorder=3,
            edgecolors="#1c2833",
            linewidths=0.7,
        )
        ax.annotate(
            name.replace("faithful_", ""),
            (grit, gender),
            fontsize=7.0,
            xytext=(5, 4),
            textcoords="offset points",
        )
    for name, color in COLORS.items():
        ax.scatter([], [], c=color, marker="o", s=58, label=name)
    ax.axvline(LYRIC_RECALL_MIN, color="#7f8c8d", ls=":", lw=0.9)
    ax.axhline(GENDER_MOVE_MIN, color="#7f8c8d", ls=":", lw=0.9)
    ax.set_xlim(-0.05, 1.05)
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("grit lyric_recall@+1  (prefix yaml lyrics, higher is better)")
    ax.set_ylabel("gender_move  (Vocal Details free vs neu, higher is better)")
    ax.set_title(
        "Lyric-token UNI scoreboard — not the bipolar board\n"
        "grit lyrics vs gender Vocal Details; marker size = cover"
    )
    ax.legend(fontsize=7, loc="lower left", framealpha=0.92)
    ax.grid(alpha=0.22)
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_markdown(
    table: dict[str, list[dict]],
    verdict: dict,
    ranked: list[dict],
    path: Path,
) -> None:
    winner = ranked[0]
    lines = [
        "# Lyric-token UNI scoreboard",
        "",
        "Generated by `analysis/slider2d/run_lm_lyric_hold.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default",
        "(`--lm_target v9` / `--pole_mode hidden`). This is **not** the",
        "compiled bipolar `exam_score` board and is not ranked on",
        "`leak_frac` or last-50 `c+` / `p%`.",
        "",
        "Three UNI recipes, do not mix:",
        "",
        "- `faithful_plus_neu` — last-token UNI (gender / tempo).",
        "- `faithful_plus_neu_prefix` — whole-prefix hold (grit / distortion / joy).",
        "- `faithful_plus_neu_lyric` — lyric-token hold (one-recipe candidate).",
        "",
        "Both pair types sit on the **same** board:",
        "",
        "1. **Grit-like / divergent** — concept words in the caption, yaml",
        "   lyrics in the prefix. Failure sings `punk punk punk`.",
        "2. **Gender-like / close** — same room, only Vocal Details flips",
        "   woman vs ungendered. Failure pins the prefix to neu so woman",
        "   never appears.",
        "",
        "Want-box: grit `lyric_recall` HIT **and** gender_move HIT **and**",
        "cover / neu_hold stay high. Gate is the existing pair-exam",
        f"continuation floor `{EXAM_ROLL_OVERLAP:g}`.",
        "",
        f"Lyric-hold hits both: **{'yes' if verdict['lyric_hits_both'] else 'no'}**.",
        f"Last-token UNI hits gender and misses grit lyrics: **{'yes' if verdict['uni_hits_gender_misses_grit'] else 'no'}**.",
        f"Whole-prefix hold hits grit lyrics and misses gender_move: **{'yes' if verdict['prefix_hits_grit_misses_gender'] else 'no'}**.",
        "",
        "## Combined rank",
        "",
        "Want-box first, then grit lyric_recall, then gender_move, then",
        "cover. Averages are over the two required cells. `+ REF`",
        "`lyric_recall` is encode(pos), no student — the yaml line must",
        "still be there when the + caption is used without LoRA.",
        "",
        "| rank | recipe | want-box | grit lyrics | gender_move | cover | neu_hold | + REF lyrics |",
        "|---:|---|---|---|---:|---:|---:|---:|",
    ]
    for row in ranked:
        lines.append(
            "| {rank} | `{name}` | {want} | {grit} | {gender} | {cover} | {hold} | {ref} |".format(
                rank=row["rank"],
                name=row["name"],
                want=_yn(bool(row["want_box"])),
                grit=_yn(bool(row["grit_lyric_hit"])),
                gender=_yn(bool(row["gender_move_hit"])),
                cover=_f(row["cover"]),
                hold=_f(row["neu_hold"]),
                ref=_f(row["lyric_recall_ref_plus"]),
            )
        )
    lines += [
        "",
        f"Winner: `{winner['name']}` want-box "
        f"{'yes' if winner['want_box'] else 'no'} "
        f"(grit lyrics {_f(winner['lyric_recall_grit'])}, "
        f"gender_move {_f(winner['gender_move'])}).",
        "",
        "![grit lyrics vs gender_move](lm-lyric-hold/want-box.png)",
        "",
        "## Per-cell numbers",
        "",
        "| recipe | cell | lyric_recall@+1 | gender_move | cover | neu_hold | + REF lyrics | sings lyrics | sings Vocal Details |",
        "|---|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for cell in ("divergent", "close"):
        for row in table[cell]:
            lines.append(
                "| `{name}` | `{cell}` | {ly} | {gm} | {cover} | {hold} | {ref} | `{sings}` | `{vd}` |".format(
                    name=row["name"],
                    cell=cell,
                    ly=_f(row["lyric_recall"]),
                    gm=_f(row.get("gender_move")),
                    cover=_f(row["cover"]),
                    hold=_f(row["neu_hold"]),
                    ref=_f(row["lyric_recall_ref_plus"]),
                    sings=row["sings_lyric"],
                    vd=row.get("sings_vocal", ""),
                )
            )
    lines += [
        "",
        "## Train card (opt-in)",
        "",
        "`--lm_target faithful_plus_neu_lyric --pole_mode hidden`. Teacher",
        "is raw `h+` at +1 last token, `h0` at scale 0, and encode(neu)",
        "on the yaml `lyrics` span only. Vocal Details / Global Metadata /",
        "Arrangement are not held. No minus, no leftover-gate. Fail closed",
        "if the lyric span cannot be found. Last real token must be",
        "`<|audio_start|>`. Default stays `--lm_target v9` /",
        "`--pole_mode hidden`.",
        "",
        "```bash",
        "CUDA_VISIBLE_DEVICES=N python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name energy-lm-uni-lyric \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
        "  --lm_target faithful_plus_neu_lyric --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0 --device 0",
        "```",
        "",
        "v4 / uni-v1 yamls are not rewritten. Infer plus+neu with the",
        "**neutral** caption + LoRA, not the + caption.",
        "",
        "## Related cells",
        "",
        "- [lm-lyric-recall.md](lm-lyric-recall.md) — existing-metric OOD + last-token transplant.",
        "- [lm-plus-neu-exam.md](lm-plus-neu-exam.md) — last-hidden cover / neu_hold / off-caption.",
        "- [lm-plus-exam.md](lm-plus-exam.md) — plus-only cover / off-caption.",
        "- [lm-2d-scoreboard.md](lm-2d-scoreboard.md) — compiled bipolar board (not updated).",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_lyric_hold.py --out docs/lm-lyric-hold",
        "PYTHONPATH=. pytest tests/test_lm_lyric_hold.py tests/test_lm_lyric_recall.py tests/test_lm_trainer_v9.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights. Seed `0`, `400` Adam steps.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table = lyric_exam_table(steps=args.steps, seed=args.seed)
    verdict = lyric_verdict(table)
    ranked = lyric_rank(table)
    blob = {
        "scale": "lyric-token UNI scoreboard",
        "not_the_bipolar_board": True,
        "scored": [
            "lyric_recall",
            "gender_move",
            "cover",
            "neu_hold",
            "lyric_recall_ref_plus",
        ],
        "gates": {
            "lyric_recall_min": LYRIC_RECALL_MIN,
            "gender_move_min": GENDER_MOVE_MIN,
            "cover_min": PLUS_COVER_MIN,
            "neu_hold_min": PLUS_NEU_HOLD_MIN,
        },
        "recipes": [c["name"] for c in LYRIC_RECIPES],
        "cells": list(LYRIC_CELLS),
        "steps": args.steps,
        "seed": args.seed,
        "verdict": {
            k: v
            for k, v in verdict.items()
            if k not in {"last_hidden_blind", "existing_ood"}
        },
        "rank": ranked,
        "rows": table,
    }
    (args.out / "metrics.json").write_text(
        json.dumps(blob, indent=2, default=str) + "\n", encoding="utf-8"
    )
    plot_want_box(ranked, table, args.out / "want-box.png")
    write_markdown(table, verdict, ranked, _REPO / "docs" / "lm-lyric-hold.md")
    print(
        f"wrote {args.out}  lyric_hits_both={verdict['lyric_hits_both']} "
        f"uni_split={verdict['uni_hits_gender_misses_grit']} "
        f"prefix_split={verdict['prefix_hits_grit_misses_gender']}"
    )


if __name__ == "__main__":
    main()
