#!/usr/bin/env python3
"""UNI 2D expect leaderboard: one sortable number per live recipe."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.expect import (
    EXPECT_GATE,
    MISS_WEIGHT,
    TIE_WEIGHT,
    expect_rank,
    expect_table,
    expect_verdict,
)
from analysis.slider2d.lyric_gender import EXPECT_RECIPES, REQUIRED_RECIPES
from analysis.slider2d.plus_exam import PLUS_COVER_MIN
from analysis.slider2d.plus_neu_exam import PLUS_NEU_HOLD_MIN


DEFAULT_OUT = _REPO / "docs" / "lm-uni-expect"

COLORS = {
    "faithful_plus_neu": "#7d3c98",
    "faithful_plus_neu_prefix": "#2471a3",
    "faithful_plus_neu_prefix@0.25": "#5dade2",
    "faithful_plus_neu_lyric": "#1e8449",
    "faithful_plus_neu_roles": "#196f3d",
    "faithful_plus_neu_orth": "#b9770e",
}


def _f(value, spec: str = ".4f", empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _hit(flag: bool) -> str:
    return "**HIT**" if flag else "MISS"


def plot_expect(ranked: list[dict], path: Path) -> None:
    """Horizontal bars of expect, already sorted descending."""
    fig, ax = plt.subplots(figsize=(8.8, 4.8))
    names = [r["name"].replace("faithful_plus_neu", "fpn") for r in ranked]
    values = [float(r["expect"]) for r in ranked]
    colors = [COLORS.get(r["name"], "#7f8c8d") for r in ranked]
    y = list(range(len(ranked)))
    ax.barh(y, values, color=colors, edgecolor="#1c2833", linewidth=0.6)
    ax.invert_yaxis()
    ax.set_yticks(y, names, fontsize=8)
    ax.set_xlabel("expect  (higher = more likely to work live on grit AND gender)")
    ax.set_title("UNI 2D expect leaderboard — not the bipolar exam_score board")
    ax.axvline(EXPECT_GATE, color="#7f8c8d", ls=":", lw=0.9, label=f"gate {EXPECT_GATE:g}")
    ax.set_xlim(min(-0.2, min(values) - 0.05), max(1.05, max(values) + 0.02))
    for yi, value in zip(y, values):
        ax.text(value + 0.01, yi, f"{value:.4f}", va="center", fontsize=8)
    ax.legend(fontsize=7, loc="lower right", framealpha=0.92)
    ax.grid(axis="x", alpha=0.22)
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_markdown(ranked: list[dict], verdict: dict, path: Path) -> None:
    winner = ranked[0]
    lines = [
        "# UNI 2D expect leaderboard",
        "",
        "Generated by `analysis/slider2d/run_lm_expect.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default",
        "(`--lm_target v9` / `--pole_mode hidden`). This is **not** the",
        "compiled bipolar `exam_score` board and is not ranked on",
        "`leak_frac` or last-50 `c+` / `p%`.",
        "",
        "One sortable number per live UNI recipe: **how good we expect it",
        "to be live on both grit lyrics and gender.** Same fixture, same",
        "seed. Joint cell is the PR #52 lyric/gender exam, scored with the",
        "live `--lm_target` losses already on main (`#50` lyric, `#49`",
        "roles, `#51` orth). Those flags are not re-implemented here.",
        "",
        f"**#1 is `{winner['name']}` at expect `{_f(winner['expect'])}`.**",
        "",
        "## Sorted expect",
        "",
    ]
    for row in ranked:
        lines.append(f"{row['rank']}. `{row['name']}` — **{_f(row['expect'])}**")
    lines += [
        "",
        "## Table",
        "",
        "Sorted by `expect` descending. `cover` is the mean of grit and",
        "gender covers. `neu_hold` is the worse of the two cells.",
        "",
        "| rank | recipe | expect | grit lyric | gender_move | cover | neu_hold |",
        "|---:|---|---:|---:|---:|---:|---:|",
    ]
    for row in ranked:
        lines.append(
            "| {rank} | `{name}` | {expect} | {lyric} | {move} | {cover} | {hold} |".format(
                rank=row["rank"],
                name=row["name"],
                expect=_f(row["expect"]),
                lyric=_f(row["grit_lyric_recall"]),
                move=_f(row["gender_move"]),
                cover=_f(row["cover"]),
                hold=_f(row["neu_hold"]),
            )
        )
    lines += [
        "",
        f"![expect, sorted](lm-uni-expect/expect.png)",
        "",
        "## The number",
        "",
        "Gates are the existing pair-exam floor: lyric_recall ≥ "
        f"`{EXPECT_GATE:g}`, gender_move ≥ `{EXPECT_GATE:g}`, cover ≥ "
        f"`{PLUS_COVER_MIN:g}`, neu_hold ≥ `{PLUS_NEU_HOLD_MIN:g}`.",
        "",
        "```",
        "bottleneck = min(grit_lyric_recall, gender_move, grit_cover, gender_cover, neu_hold)",
        f"expect     = bottleneck",
        f"           - {MISS_WEIGHT:g} * max(0, {EXPECT_GATE:g} - grit_lyric_recall)",
        f"           - {MISS_WEIGHT:g} * max(0, {EXPECT_GATE:g} - gender_move)",
        f"           + {TIE_WEIGHT:g} * (0.50 * leftover_cover",
        "                          + 0.30 * leftover_neu_hold",
        "                          + 0.20 * unused_off_caption_slack)",
        "```",
        "",
        "Why the extra term: the suggested `min` plus miss penalties already",
        "rank a cover-collapse lyric-saver below a recipe that keeps `h+`.",
        "Without a leftover, two HITs with the same bottleneck print the",
        "same 1.000. Residual cover / neu_hold / unused off-caption slack",
        f"are scaled by `{TIE_WEIGHT:g}` so they cannot flip a gate miss",
        "(`0.15`) or a `0.05` bottleneck gap.",
        "",
        "Required live recipes: "
        + ", ".join(f"`{n}`" for n in REQUIRED_RECIPES)
        + ". Optional ablation: `faithful_plus_neu_prefix@0.25` via the",
        "already-wired `prefix_weight` on `lm_plus_neu_prefix_loss`.",
        "",
        "## Both pair types, one board",
        "",
        "1. **Grit-like / divergent** — yaml lyrics in the prefix, concept",
        "   words in the + caption. Fail = sings `punk punk`.",
        "2. **Gender-like / close** — same room, only Vocal Details flips",
        "   woman vs ungendered. Fail = pinned to neu / `gender_move` miss.",
        "",
        "## Per-cell rows",
        "",
        "### grit-like / divergent",
        "",
        "| recipe | lyric_recall | cover | neu_hold | sings lyrics |",
        "|---|---:|---:|---:|---|",
    ]
    for row in ranked:
        grit = row["grit"]
        lines.append(
            "| `{name}` | {ly} | {cover} | {hold} | `{sings}` |".format(
                name=row["name"],
                ly=_f(grit["lyric_recall"]),
                cover=_f(grit["cover"]),
                hold=_f(grit["neu_hold"]),
                sings=grit.get("sings_lyric", ""),
            )
        )
    lines += [
        "",
        "### gender-like / close",
        "",
        "| recipe | gender_move | cover | neu_hold | Vocal Details @ +1 |",
        "|---|---:|---:|---:|---|",
    ]
    for row in ranked:
        close = row["close"]
        lines.append(
            "| `{name}` | {move} | {cover} | {hold} | `{vd}` |".format(
                name=row["name"],
                move=_f(close.get("gender_move")),
                cover=_f(close["cover"]),
                hold=_f(close["neu_hold"]),
                vd=close.get("reads_vocal_plus", ""),
            )
        )
    lines += [
        "",
        "## Recipe cards (opt-in, already on main)",
        "",
    ]
    for cand in EXPECT_RECIPES:
        lines.append(f"- `{cand['name']}` — {cand['is']}")
    lines += [
        "",
        "Default stays `--lm_target v9` / `--pole_mode hidden`.",
        "No Music 3 train, no GPU, no Hub, no weights on this page.",
        "",
        "## Related cells",
        "",
        "- [lm-lyric-hold.md](lm-lyric-hold.md) — lyric-token hold board (#50).",
        "- [lm-roles.md](lm-roles.md) — role-split board (#49).",
        "- [lm-lyric-orth.md](lm-lyric-orth.md) — last-delta / lyric-span board (#51).",
        "- [lm-plus-neu-exam.md](lm-plus-neu-exam.md) — last-hidden cover / neu_hold.",
        "- [lm-2d-scoreboard.md](lm-2d-scoreboard.md) — compiled bipolar board (not updated).",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_expect.py --out docs/lm-uni-expect",
        "PYTHONPATH=. pytest tests/test_lm_uni_expect.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights. Seed `0`, `400` Adam steps.",
        "",
        f"Winner: `{winner['name']}` expect {_f(winner['expect'])}"
        f" (grit lyric {_f(winner['grit_lyric_recall'])},"
        f" gender_move {_f(winner['gender_move'])},"
        f" cover {_f(winner['cover'])},"
        f" neu_hold {_f(winner['neu_hold'])}).",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table = expect_table(steps=args.steps, seed=args.seed)
    ranked = expect_rank(table)
    verdict = expect_verdict(table)
    blob = {
        "scale": "UNI 2D expect leaderboard",
        "not_the_bipolar_board": True,
        "scored": ["expect", "grit_lyric_recall", "gender_move", "cover", "neu_hold"],
        "not_scored": ["exam_score", "leak_frac", "c+", "p%"],
        "gates": verdict["gates"],
        "formula": verdict["formula"],
        "recipes": [c["name"] for c in EXPECT_RECIPES],
        "required": list(REQUIRED_RECIPES),
        "steps": args.steps,
        "seed": args.seed,
        "verdict": {k: v for k, v in verdict.items() if k != "formula"},
        "rank": [
            {k: v for k, v in row.items() if k not in {"grit", "close"}}
            for row in ranked
        ],
        "rows": table,
    }
    (args.out / "metrics.json").write_text(
        json.dumps(blob, indent=2, default=str) + "\n", encoding="utf-8"
    )
    plot_expect(ranked, args.out / "expect.png")
    write_markdown(ranked, verdict, _REPO / "docs" / "lm-uni-expect.md")
    print(
        f"wrote {args.out}  #1={verdict['winner']} "
        f"expect={verdict['winner_expect']:.4f} "
        f"unique={verdict['unique_expect']}"
    )


if __name__ == "__main__":
    main()
