#!/usr/bin/env python3
"""Plus-only exam: cover vs off-caption on the + pole. Separate scale."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.plus_exam import (
    PLUS_CELLS,
    PLUS_COVER_MIN,
    PLUS_OFF_MAX,
    PLUS_RECIPES,
    plus_exam_table,
    plus_helps,
)


DEFAULT_OUT = _REPO / "docs" / "lm-plus-exam"


def _f(value, spec: str = ".3f", empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def plot_plus_scale(table: dict[str, list[dict]], path: Path) -> None:
    """cover vs off-caption. Want-box is high cover, off-caption near 0."""
    fig, ax = plt.subplots(figsize=(8.4, 5.4))
    marks = {"divergent": "o", "close": "s", "unused_e": "^"}
    colors = {
        "faithful_plus": "#1e8449",
        "leftover_gate_bipolar": "#2471a3",
        "faithful_even_blend": "#b9770e",
        "pair_odd_midpoint": "#c0392b",
    }
    want = Rectangle(
        (0.0, PLUS_COVER_MIN),
        PLUS_OFF_MAX,
        1.0 - PLUS_COVER_MIN,
        facecolor="#d5f5e3",
        edgecolor="#1e8449",
        lw=1.0,
        alpha=0.55,
        zorder=1,
        label="want-box (high cover, off-caption ≤ 0.05)",
    )
    ax.add_patch(want)
    for cell, rows in table.items():
        for row in rows:
            ax.scatter(
                [row["off_caption"]],
                [row["cover"]],
                c=colors.get(row["name"], "#7f8c8d"),
                marker=marks.get(cell, "o"),
                s=72,
                zorder=3,
                edgecolors="white",
                linewidths=0.7,
            )
            ax.annotate(
                f"{row['name']}\n{cell}",
                (row["off_caption"], row["cover"]),
                fontsize=6.4,
                xytext=(5, 4),
                textcoords="offset points",
            )
    for name, color in colors.items():
        ax.scatter([], [], c=color, marker="o", s=58, label=name)
    ax.axvline(PLUS_OFF_MAX, color="#7f8c8d", ls=":", lw=0.9)
    ax.axhline(PLUS_COVER_MIN, color="#7f8c8d", ls=":", lw=0.9)
    ax.set_xlabel("off-caption on the + continuation (lower is better)")
    ax.set_ylabel("cover of the + state  [0, 1]  (higher is better)")
    ax.set_title(
        "Plus-only scale — not the bipolar board\n"
        "cover vs off-caption on the + pole"
    )
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.05)
    ax.grid(alpha=0.25)
    ax.legend(fontsize=7.4, loc="lower right")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_markdown(
    table: dict[str, list[dict]], verdict: dict, path: Path
) -> None:
    helps = "yes" if verdict["yes"] else "no"
    lines = [
        "# Plus-only exam: cover the + pole, do not teach −1",
        "",
        "Generated by `analysis/slider2d/run_lm_plus_exam.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default",
        "(`--lm_target v9` / `--pole_mode hidden`). This is a **separate",
        "scale** from pair-exam, leftover-sheet `leak_frac`, and the compiled",
        "bipolar board. Those pages are not updated here.",
        "",
        "Bipolar ±1 is where leak_frac, midpoint Goodhart, even-blend lyric",
        "smear, and +/− same-dir leak live. The question is whether training",
        "only the positive pole alleviates a lot of that on the + continuation.",
        "",
        f"**Does plus-only help? `{helps}`** — from the two scored numbers",
        "on the same CPU fixture, not from an essay.",
        "",
        "## Two scored numbers",
        "",
        "1. **off-caption** on the + continuation: words neither the + caption",
        "   nor the pair's shared song sings. Shared song is lyrics plus tokens",
        "   both pole captions sing. Singing the − pole's unique track words",
        f"   is off-caption here. Gate: `≤ {PLUS_OFF_MAX}`. Lower is better.",
        "2. **cover** of the + state:",
        "",
        "   `cover = min(overlap_with_pos, 1 − blend_toward_mid)` in `[0, 1]`.",
        "",
        "   `overlap_with_pos` is the share of + continuation tokens that the",
        "   + caption itself sings. `blend_toward_mid` is",
        "   `‖s+ − pos‖ / (‖s+ − pos‖ + min(‖s+ − mid‖, ‖s+ − neg‖))` — 0 at",
        "   pos, 1 at mid or at neg. A hit is",
        f"   `cover ≥ {PLUS_COVER_MIN}` AND `off-caption ≤ {PLUS_OFF_MAX}`.",
        "",
        "Not scored: `leak_frac`, collapse, pair-odd cos, minus overlap,",
        "`exam_score`. −1 is an unconstrained canary in a labeled section",
        "below.",
        "",
        "## Train card (opt-in)",
        "",
        "`--lm_target faithful_plus --pole_mode hidden`. Teacher is leftover-",
        "gated `h+` (raw pos when leftover ê is unused or undeclared). Student",
        "+1 fits that + state. No pair-odd, no `h0 ± a`, no minus MSE.",
        "Inference may still expose a −1 fader; that fader is not trained.",
        "Sidecar records `lm_target` and `plus_only`. Default stays",
        "`--lm_target v9` / `--pole_mode hidden`.",
        "",
        "```bash",
        "python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name energy-lm-plus \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
        "  --lm_target faithful_plus --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0",
        "```",
        "",
        "Same card on gender-v4 (`--name gender-lm-plus`,",
        "`prompts-gender-v4.yaml`). The yaml is not rewritten. No live listen",
        "on this branch.",
        "",
        "## The board (400 Adam steps, seed 0)",
        "",
        "Per + pole, not a ± pair. `leftover_gate_bipolar` is the current",
        "`faithful` / leftover-gate +/− teacher. `faithful_even_blend` is the",
        "v21 bipolar even-blend (`α = 0.5`). `pair_odd_midpoint` is the known",
        "fail.",
        "",
    ]
    for cell in PLUS_CELLS:
        rows = table[cell]
        lines += [
            f"### `{cell}`",
            "",
            "| recipe | train | cover | off-caption | overlap+ | blend→mid | hit |",
            "|---|---|---:|---:|---:|---:|---|",
        ]
        for row in rows:
            lines.append(
                "| `{name}` | {train} | {cover} | {off} | {ov} | {blend} | {hit} |".format(
                    name=row["name"],
                    train="plus-only" if row["plus_only"] else "bipolar ±",
                    cover=_f(row["cover"]),
                    off=_f(row["off_caption"]),
                    ov=_f(row["overlap_pos"]),
                    blend=_f(row["blend_toward_mid"]),
                    hit="**HIT**" if row["hit"] else "—",
                )
            )
        lines.append("")
    lines += [
        "![cover vs off-caption on the plus-only scale](lm-plus-exam/plus-scale.png)",
        "",
        "Want-box is high cover, off-caption near 0. Title says this is the",
        "plus-only scale, not the bipolar board.",
        "",
        "## Unscored canary: what −1 does",
        "",
        "Inference may still expose a −1 fader. Plus-only does not train it.",
        "Logged here only. Not a score. `dangerous` is same-dir (landed on +)",
        "or −1 off-caption above the 0.05 suggestion.",
        "",
        "| cell | recipe | −1 landed | −1 overlap with − | −1 off-caption | dangerous? |",
        "|---|---|---|---:|---:|---|",
    ]
    for cell, rows in table.items():
        for row in rows:
            can = row["canary"]
            lines.append(
                "| `{cell}` | `{name}` | {land} | {ov} | {off} | {dang} |".format(
                    cell=cell,
                    name=row["name"],
                    land=can["minus_landed"],
                    ov=_f(can["minus_overlap_neg"]),
                    off=_f(can["minus_off_caption"]),
                    dang="**yes**" if can["dangerous"] else "no",
                )
            )
    lines += [
        "",
        "## What the numbers say",
        "",
        f"- Plus-only hits both required pairs: **{verdict['plus_hits_required']}**.",
        f"- Bipolar hits on those pairs: `{verdict['bipolar_hits']}`.",
        f"- Plus-only is materially cleaner than leftover-gate on +: "
        f"**{verdict['beats_leftover_gate']}**.",
        f"- Bipolar recipes plus-only alleviates on this scale: "
        f"`{verdict['alleviates'] or 'none'}` (they miss a hit that plus-only makes).",
        "",
        f"**Answer: {helps}.** Training only + does "
        + (
            "alleviate the bipolar fails this scale can see "
            "(midpoint / even-blend smear on the + continuation)."
            if verdict["yes"]
            else (
                "not beat leftover-gate bipolar on the + pole — the ± "
                "pathologies live in the pair, which this scale does not score."
            )
        ),
        "",
        "## Related cells (not this scale)",
        "",
        "- [lm-pair-exam.md](lm-pair-exam.md) — bipolar continuation gates.",
        "- [lm-even-leftover.md](lm-even-leftover.md) — leftover-sheet `leak_frac`.",
        "- [lm-2d-scoreboard.md](lm-2d-scoreboard.md) — compiled bipolar board.",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_plus_exam.py --out docs/lm-plus-exam",
        "PYTHONPATH=. pytest tests/test_lm_plus_exam.py tests/test_lm_trainer_v9.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights. Seed `0`, `400` Adam steps.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table = plus_exam_table(steps=args.steps, seed=args.seed)
    verdict = plus_helps(table)
    blob = {
        "scale": "plus-only",
        "not_the_bipolar_board": True,
        "scored": ["cover", "off_caption"],
        "not_scored": [
            "leak_frac",
            "collapse",
            "pair_odd_cos",
            "minus_overlap",
            "exam_score",
        ],
        "gates": {"cover_min": PLUS_COVER_MIN, "off_caption_max": PLUS_OFF_MAX},
        "recipes": [c["name"] for c in PLUS_RECIPES],
        "cells": list(PLUS_CELLS),
        "steps": args.steps,
        "seed": args.seed,
        "helps": verdict,
        "rows": table,
    }
    (args.out / "metrics.json").write_text(
        json.dumps(blob, indent=2, default=str) + "\n", encoding="utf-8"
    )
    plot_plus_scale(table, args.out / "plus-scale.png")
    write_markdown(table, verdict, _REPO / "docs" / "lm-plus-exam.md")
    print(f"wrote {args.out}  helps={verdict['yes']}")


if __name__ == "__main__":
    main()
