#!/usr/bin/env python3
"""Student-apart regularizer: caption teacher, push ±1 apart.

Sweeps even / cos / same_dir weights on the pair-exam cells. Teacher stays
``faithful`` (t± = h±). A win is exam_divergent True and leak_frac < 0
without falling into the leak_frac ≈ −1 midpoint well. CPU only. No Hub,
no GPU, no Music 3 weights. Does not change the live trainer default.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.exam import (
    APART_MIDPOINT_LEAK,
    APART_SWEEP_KINDS,
    APART_WEIGHTS,
    apart_sweep,
    pick_apart_win,
)
from analysis.slider2d.sheet import leaky_field, score_sheet


DEFAULT_OUT = _REPO / "docs" / "lm-student-apart"


def leftover_leaks(
    *,
    kinds: tuple[str, ...] = APART_SWEEP_KINDS,
    weights: tuple[float, ...] = APART_WEIGHTS,
    steps: int = 400,
    seed: int = 0,
) -> dict[tuple[str, float], dict]:
    """Unused-ê leftover sheet for each (kind, weight). Teacher is faithful."""
    field = leaky_field()
    out: dict[tuple[str, float], dict] = {}
    for kind in kinds:
        for weight in weights:
            row = score_sheet(
                f"apart_{kind}_w{weight:g}",
                field,
                pole_mode="hidden",
                teacher="faithful",
                apart_weight=float(weight),
                apart_kind=kind,
                steps=steps,
                seed=seed,
            )
            out[(kind, float(weight))] = row
    return out


def _fmt(value, spec: str, empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _pass(flag: bool | None) -> str:
    if flag is True:
        return "pass"
    if flag is False:
        return "**fail**"
    return "—"


def _win_tag(row: dict) -> str:
    if row.get("win"):
        return "**win**"
    if row.get("pair_odd_like") and not row.get("exam_divergent"):
        return "pair-odd (banned)"
    if row.get("exam_divergent") and row.get("leak_frac") is not None and float(row["leak_frac"]) < 0:
        return "divergent+neg (in −1 well)"
    if row.get("exam_divergent"):
        return "divergent, leak_frac≥0"
    return "fail divergent"


def plot_sweep(sweep: list[dict], path: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(10.4, 4.4))
    colors = {"even": "#1e8449", "cos": "#2471a3", "same_dir": "#a04000"}
    marks = {"even": "o", "cos": "s", "same_dir": "^"}
    for kind, color in colors.items():
        rows = [r for r in sweep if r["apart_kind"] == kind]
        xs = [r["apart_weight"] for r in rows]
        axes[0].plot(
            xs,
            [r["leak_frac"] for r in rows],
            color=color,
            marker=marks[kind],
            label=kind,
        )
        axes[1].plot(
            xs,
            [1.0 if r["exam_divergent"] else 0.0 for r in rows],
            color=color,
            marker=marks[kind],
            label=kind,
        )
    axes[0].axhline(0.0, color="#7f8c8d", lw=1)
    axes[0].axhline(APART_MIDPOINT_LEAK, color="#c0392b", ls="--", lw=1, label="−1 well")
    axes[0].set_xscale("symlog", linthresh=0.02)
    axes[0].set_xlabel("apart weight")
    axes[0].set_ylabel("leak_frac (divergent student)")
    axes[0].set_title("cos(d+, d−) vs weight")
    axes[0].legend(loc="lower left", fontsize=8)
    axes[1].set_xscale("symlog", linthresh=0.02)
    axes[1].set_xlabel("apart weight")
    axes[1].set_ylabel("exam_divergent")
    axes[1].set_ylim(-0.05, 1.05)
    axes[1].set_title("divergent pair pass")
    axes[1].legend(loc="lower left", fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_md(
    path: Path,
    *,
    sweep: list[dict],
    leftover: dict[tuple[str, float], dict],
    win: dict | None,
    wired: bool,
) -> None:
    lines = [
        "# Student-apart regularizer: caption teacher, push ±1 apart",
        "",
        "Generated by `analysis/slider2d/run_lm_apart.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default.",
        "",
        "The teacher stays a real caption (`t± = h±`, `--lm_target faithful`).",
        "The new term is on the **student**: +1 and −1 are pushed apart so",
        "`leak_frac = cos(d+, d−)` of the fitted leftover-bipolar residual",
        "goes down, without moving the target to the midpoint. Three kinds:",
        "",
        "- `even` — `‖½(d+ + d−)‖²` (mean-squared, same scale as pole MSE)",
        "- `cos` — `cos(d+, d−)` itself (leak_frac)",
        "- `same_dir` — `‖even‖ / (‖even‖ + ‖odd‖)`",
        "",
        "Caption poles pass `exam_divergent` and sit at leak_frac +0.03 to",
        "+0.12. Pair-odd / midpoint / hub / project sit at −1 and fail energy.",
        "`faithful_attrs` (leak_frac −0.08, divergent pass) is a data pin,",
        "not a train recipe. leak_frac ≈ −1 that fails divergent is the",
        "midpoint Goodhart (v14/v15). Banned. A regularizer that secretly",
        "implements pair-odd fails the same way and is not a win.",
        "",
        "## The criterion",
        "",
        "`exam_divergent` must be True. `leak_frac` of the fitted ±1 student",
        "on that pair must be negative, and must stay above",
        f"`{APART_MIDPOINT_LEAK}` so the row is not the −1 well.",
        "",
    ]
    if win is None:
        lines += [
            "## Verdict",
            "",
            "**No train recipe.** Every weight that drives leak_frac below 0",
            "also fails `exam_divergent`, or lands in the −1 well. The",
            "regularizer is pair-odd in disguise once it is strong enough to",
            "flip the sign. Live default stays `--lm_target v9` /",
            "`--pole_mode hidden`. No live flag is wired.",
            "",
        ]
    else:
        lines += [
            "## Verdict",
            "",
            f"**`{win['name']}`** — `--lm_target faithful --pole_mode hidden` ",
            f"plus `--apart_kind {win['apart_kind']} --apart_weight {win['apart_weight']:g}`.",
            f"exam_divergent **pass**, leak_frac {win['leak_frac']:+.3f},",
            f"exam_close {_pass(win['exam_close'])}, leftover leak",
            f"{_fmt(win.get('leftover_leak'), '+.3f')}.",
            "Teacher is still the caption. Live default is unchanged.",
            "",
        ]
        if wired:
            lines += [
                "```bash",
                "python conceptmod/textsliders/train_lm_slider_music3.py \\",
                "  --name energy-lm-apart \\",
                "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
                f"  --lm_target faithful --pole_mode hidden \\",
                f"  --apart_kind {win['apart_kind']} --apart_weight {win['apart_weight']:g} \\",
                "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
                "  --no-early_stop --endreg_weight 1.0",
                "```",
                "",
                "This is not a live listen. The card is the CPU exam only.",
                "",
            ]

    lines += [
        "## Weight sweep",
        "",
        "Teacher `faithful`, pole_mode `hidden`. `leak_frac` is",
        "`leftover_bipolar` of the divergent-pair student. leftover leak",
        "is unused-ê `leak_tok` on the #22 leftover sheet, same teacher",
        "and regularizer. Neither leftover leak nor pair-odd cos is scored.",
        "",
        "| kind | weight | exam_divergent | exam_close | leak_frac | leftover leak | same_dir | tag |",
        "|---|---:|---|---|---:|---:|---:|---|",
    ]
    for row in sweep:
        lines.append(
            f"| `{row['apart_kind']}` | {row['apart_weight']:g} | "
            f"{_pass(row['exam_divergent'])} | {_pass(row['exam_close'])} | "
            f"{row['leak_frac']:+.3f} | {_fmt(row.get('leftover_leak'), '+.3f')} | "
            f"{row['same_dir']:.3f} | {_win_tag(row)} |"
        )
    lines += [
        "",
        "![leak_frac and exam_divergent vs weight](lm-student-apart/sweep.png)",
        "",
        "## What each kind does",
        "",
        "The student is `δ(σ) = σ·w_odd + |σ|·w_even`, so",
        "`d+ = w_odd + w_even`, `d− = −w_odd + w_even`, and",
        "`leak_frac = (‖even‖² − ‖odd‖²) / (‖even‖² + ‖odd‖²)`.",
        "Faithful MSE wants `w_even = c`. The regularizer wants",
        "`w_even → 0`. Equilibrium is `w_even = c / (1 + λ')`. At",
        "`λ' = 0` leak_frac is the caption value (slightly positive on",
        "energy-v4). At `λ' → ∞` the student is pair-odd and sings both",
        "tracks. The question is whether leak_frac crosses 0 while the",
        "continuation still stays on one song.",
        "",
        "## Live default",
        "",
        "Unchanged: `--lm_target v9` / `--pole_mode hidden`. v4 yamls are",
        "not rewritten. No live listen is invented.",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_apart.py --out docs/lm-student-apart",
        "PYTHONPATH=. pytest tests/test_lm_student_apart.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights.",
        "",
        "Pair-exam `400` steps, 8-token rollout, 4 draws; leftover sheet",
        "`400` Adam steps. Seed `0`.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    p.add_argument("--steps", type=int, default=400)
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args(argv)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    leftover = leftover_leaks(steps=args.steps, seed=args.seed)
    leaks = {key: float(row.get("leak_tok", 0.0)) for key, row in leftover.items()}
    sweep = apart_sweep(steps=args.steps, seed=args.seed, leftover_leaks=leaks)
    win = pick_apart_win(sweep)
    wired = win is not None

    plot_sweep(sweep, out / "sweep.png")
    write_md(out.parent / "lm-student-apart.md", sweep=sweep, leftover=leftover, win=win, wired=wired)

    payload = {
        "sweep": sweep,
        "win": win,
        "wired": wired,
        "leftover": {
            f"{kind}:{weight:g}": {
                "leak_tok": float(row.get("leak_tok", 0.0)),
                "leak_frac": float(row.get("leak_frac", row.get("collapse", 0.0))),
                "on_sheet_kept": float(row.get("on_sheet_kept", 0.0)),
            }
            for (kind, weight), row in leftover.items()
        },
    }
    (out / "metrics.json").write_text(json.dumps(payload, indent=2) + "\n")
    print(json.dumps({"win": win, "n": len(sweep)}, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
