#!/usr/bin/env python3
"""Last-delta / lyric-span projection UNI board. Separate from prefix-hold."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.exam import EXAM_ROLL_OVERLAP
from analysis.slider2d.lyric_recall import (
    GENDER_MOVE_MIN,
    LYRIC_CELLS,
    LYRIC_RECALL_MIN,
    LYRIC_RECIPES,
    lyric_exam_table,
    lyric_rank,
    lyric_verdict,
)
from analysis.slider2d.plus_exam import PLUS_COVER_MIN
from analysis.slider2d.plus_neu_exam import PLUS_NEU_HOLD_MIN


DEFAULT_OUT = _REPO / "docs" / "lm-lyric-orth"

COLORS = {
    "faithful_plus_neu": "#1e8449",
    "faithful_plus_neu_prefix": "#b9770e",
    "faithful_plus_neu_orth": "#1a5276",
    "faithful_plus": "#7d3c98",
    "leftover_gate_bipolar": "#2471a3",
    "pair_odd_midpoint": "#c0392b",
}
MARKS = {"divergent": "o", "close": "s"}


def _f(value, spec: str = ".3f", empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _hit(flag: bool) -> str:
    return "**HIT**" if flag else "MISS"


def plot_lyric_orth(table: dict[str, list[dict]], path: Path) -> None:
    """lyric_recall vs gender_move. Want-box is high both."""
    fig, ax = plt.subplots(figsize=(8.8, 5.8))
    want = Rectangle(
        (LYRIC_RECALL_MIN, GENDER_MOVE_MIN),
        1.0 - LYRIC_RECALL_MIN,
        1.0 - GENDER_MOVE_MIN,
        facecolor="#d5f5e3",
        edgecolor="#1e8449",
        lw=1.0,
        alpha=0.55,
        zorder=1,
        label="want-box (grit lyric HIT AND gender_move HIT)",
    )
    ax.add_patch(want)
    for cell, rows in table.items():
        for row in rows:
            ax.scatter(
                [row["lyric_recall"]],
                [row["gender_move"]],
                c=[COLORS.get(row["name"], "#7f8c8d")],
                marker=MARKS.get(cell, "o"),
                s=90 if row["name"].startswith("faithful_plus_neu") else 64,
                zorder=3,
                edgecolors="#1c2833",
                linewidths=0.7,
            )
            ax.annotate(
                f"{row['name']}\n{cell}",
                (row["lyric_recall"], row["gender_move"]),
                fontsize=6.2,
                xytext=(5, 4),
                textcoords="offset points",
            )
    for name, color in COLORS.items():
        ax.scatter([], [], c=color, marker="o", s=58, label=name)
    ax.axvline(LYRIC_RECALL_MIN, color="#7f8c8d", ls=":", lw=0.9)
    ax.axhline(GENDER_MOVE_MIN, color="#7f8c8d", ls=":", lw=0.9)
    ax.set_xlabel("lyric_recall @ +1  [0, 1]  (higher is better)")
    ax.set_ylabel("gender_move @ +1  [0, 1]  (higher is better)")
    ax.set_title(
        "UNI last-delta / lyric-span projection\n"
        "lyric_recall vs gender_move — not whole-prefix hold, not lyric-token hold"
    )
    ax.set_xlim(-0.02, 1.05)
    ax.set_ylim(-0.02, 1.05)
    ax.grid(alpha=0.25)
    ax.legend(fontsize=6.8, loc="lower left")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_markdown(
    table: dict[str, list[dict]],
    verdict: dict,
    ranked: list[dict],
    path: Path,
) -> None:
    beats = "yes" if verdict.get("orth_beats_split") else "no"
    lines = [
        "# UNI last-delta / lyric-span projection",
        "",
        "Generated by `analysis/slider2d/run_lm_lyric_orth.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default",
        "(`--lm_target v9` / `--pole_mode hidden`). This is a **separate",
        "board** from the existing-metric OOD hunt, whole-prefix hold, and",
        "lyric-token hold MSE. Those pages are not replaced here.",
        "",
        "`faithful_plus_neu` (last-token UNI) keeps gender/tempo lyrics and",
        "flips woman, but shreds grit/distortion/joy lyrics: last-token",
        "transplant. `faithful_plus_neu_prefix` holds the entire +1 prefix",
        "to encode(neu). That restores grit lyrics and pins Vocal Details",
        "so woman cannot appear.",
        "",
        f"**Does last-delta / lyric-span projection beat that split? `{beats}`**",
        "— grit lyric HIT and gender_move HIT on one board, from the",
        "scored numbers, not from an essay.",
        "",
        "## Scored numbers",
        "",
        "1. **lyric_recall@+1** on the prefix sung line vs the yaml lyric",
        "   sheet (existing pair-exam continuation floor).",
        "",
        f"   Gate: `≥ {LYRIC_RECALL_MIN}`. Higher is better.",
        "2. **cover** of the + state (same as plus-only / plus+neu).",
        "",
        f"   Gate: `≥ {PLUS_COVER_MIN}`. Higher is better.",
        "3. **neu_hold** at scale 0 (same as plus+neu).",
        "",
        f"   Gate: `≥ {PLUS_NEU_HOLD_MIN}`. Higher is better.",
        "4. **gender_move**: Vocal Details at +1 may differ from neu.",
        "   Prefix-hold zeros the prefix residual (miss). Last-token UNI",
        "   and last-delta-orth leave it free.",
        "",
        f"   Gate: `≥ {GENDER_MOVE_MIN}`. Higher is better.",
        "",
        "Want-box: grit lyric HIT **and** gender_move HIT. Rank is want-box",
        "first, then lyric_recall, cover, neu_hold, gender_move.",
        "Not ranked: `exam_score`, `leak_frac`, `c+`, `p%`.",
        "",
        "## Train card (opt-in)",
        "",
        "`--lm_target faithful_plus_neu_orth --pole_mode hidden`. Last-token",
        "UNI stays: +1 last → raw `h+`, 0 → `h0`, no minus, no leftover-gate.",
        "The last-token update must not lie in the lyric-token hidden span.",
        "Lyric tokens keep only the in-span residual. Vocal Details are not",
        "held. Fail closed if the lyric span cannot be found. Last token",
        "must be `<|audio_start|>`. Infer with the yaml `neutral` caption +",
        "LoRA. Default stays `--lm_target v9` / `--pole_mode hidden`.",
        "`faithful_plus_neu` and `faithful_plus_neu_prefix` are unchanged.",
        "",
        "```bash",
        "CUDA_VISIBLE_DEVICES=N python conceptmod/textsliders/train_lm_slider_music3.py \\",
        "  --name energy-lm-uni-orth \\",
        "  --prompts_file conceptmod/textsliders/data/prompts-energy-v4.yaml \\",
        "  --lm_target faithful_plus_neu_orth --pole_mode hidden \\",
        "  --rank 8 --alpha 8 --lr 5e-4 --steps 800 --seed 7 \\",
        "  --no-early_stop --endreg_weight 1.0 --device 0",
        "```",
        "",
        "v4 yaml is the fixture rank. The yaml is not rewritten. No live",
        "listen on this branch.",
        "",
        "## Combined rank (divergent + close)",
        "",
        "Want-box first (grit lyric HIT and gender_move HIT, plus cover /",
        "neu_hold), then lyric_recall, cover, neu_hold, gender_move.",
        "Averages over the two required cells.",
        "",
        "| rank | recipe | want-box | lyric_recall | cover | neu_hold | gender_move | grit lyric | gender |",
        "|---:|---|---|---:|---:|---:|---:|---|---|",
    ]
    for row in ranked:
        lines.append(
            "| {rank} | `{name}` | {box} | {lyric} | {cover} | {hold} | {g} | {gl} | {gm} |".format(
                rank=row["rank"],
                name=row["name"],
                box="**yes**" if row.get("want_box") else "—",
                lyric=_f(row["lyric_recall"]),
                cover=_f(row["cover"]),
                hold=_f(row["neu_hold"]),
                g=_f(row.get("gender_move")),
                gl=_hit(bool(row.get("grit_lyric_hit"))),
                gm=_hit(bool(row.get("gender_move_hit"))),
            )
        )
    lines += [
        "",
        "## The board (400 Adam steps, seed 0)",
        "",
        "Both pair types on one board:",
        "",
        "1. **grit-like / divergent** — yaml lyrics in prefix, concept words",
        "   in the + caption. Fail = sings `punk punk`.",
        "2. **gender-like / close** — same room, only Vocal Details flips",
        "   woman vs ungendered. Fail = woman pinned away / gender_move miss.",
        "",
        "Baselines: `faithful_plus_neu` (gender HIT, grit MISS) and",
        "`faithful_plus_neu_prefix` (grit HIT, gender MISS).",
        "",
    ]
    for cell in LYRIC_CELLS:
        rows = table[cell]
        lines += [
            f"### `{cell}`",
            "",
            "| recipe | lyric_recall | cover | neu_hold | gender_move | sings lyric | want-box |",
            "|---|---:|---:|---:|---:|---|---|",
        ]
        for row in rows:
            lines.append(
                "| `{name}` | {lyric} | {cover} | {hold} | {g} | {sings} | {want} |".format(
                    name=row["name"],
                    lyric=_f(row["lyric_recall"]),
                    cover=_f(row["cover"]),
                    hold=_f(row["neu_hold"]),
                    g=_f(row.get("gender_move")),
                    sings=row.get("sings_lyric", ""),
                    want="**yes**" if row.get("want_box") else "—",
                )
            )
        lines.append("")
    lines += [
        "![lyric_recall vs gender_move](lm-lyric-orth/lyric-orth-scale.png)",
        "",
        "Want-box is high lyric_recall AND high gender_move. Circles are",
        "divergent / grit-like; squares are close / gender-like.",
        "",
        "## Baselines vs last-delta-orth",
        "",
        f"- UNI grit lyric miss: **{'yes' if verdict.get('uni_grit_lyric_miss') else 'no'}**",
        f"  (`{', '.join(_f(x) for x in verdict.get('uni_lyric_recall', []))}`).",
        f"- UNI gender_move hit: **{'yes' if verdict.get('uni_gender_hit') else 'no'}**",
        f"  (`{', '.join(_f(x) for x in verdict.get('uni_gender_move', []))}`).",
        f"- Prefix grit lyric hit: **{'yes' if verdict.get('prefix_grit_lyric_hit') else 'no'}**",
        f"  (`{', '.join(_f(x) for x in verdict.get('prefix_lyric_recall', []))}`).",
        f"- Prefix gender_move miss: **{'yes' if verdict.get('prefix_gender_miss') else 'no'}**",
        f"  (`{', '.join(_f(x) for x in verdict.get('prefix_gender_move', []))}`).",
        f"- Orth beats the split: **{beats}**",
        f"  (lyric `{', '.join(_f(x) for x in verdict.get('orth_lyric_recall', []))}`,",
        f"  gender_move `{', '.join(_f(x) for x in verdict.get('orth_gender_move', []))}`,",
        f"  cover `{', '.join(_f(x) for x in verdict.get('orth_cover', []))}`).",
        "",
        "**Answer: want-box `{beats}`.** Last-token UNI plus a last-delta / "
        "{tail}".format(
            beats=beats,
            tail=(
                "lyric-span projection keeps grit lyrics without holding Vocal "
                "Details to neu."
                if verdict.get("orth_beats_split")
                else "lyric-span projection did not beat the UNI / prefix-hold "
                "split on this fixture."
            ),
        ),
        "",
        "## Related cells",
        "",
        "- [lm-lyric-recall.md](lm-lyric-recall.md) — existing-metric OOD + last-token transplant.",
        "- [lm-plus-neu-exam.md](lm-plus-neu-exam.md) — last-hidden cover / neu_hold / off-caption.",
        "- [lm-plus-exam.md](lm-plus-exam.md) — plus-only cover / off-caption.",
        "- [lm-2d-scoreboard.md](lm-2d-scoreboard.md) — compiled bipolar board (not updated).",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_lyric_orth.py --out docs/lm-lyric-orth",
        "PYTHONPATH=. pytest tests/test_lm_lyric_recall.py tests/test_lm_trainer_v9.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights. Seed `0`, `400` Adam steps.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table = lyric_exam_table(steps=args.steps, seed=args.seed)
    verdict = lyric_verdict(table)
    ranked = lyric_rank(table)
    blob = {
        "scale": "plus+neu last-delta / lyric-span projection",
        "not_the_bipolar_board": True,
        "not_prefix_hold": True,
        "not_lyric_token_hold": True,
        "scored": ["lyric_recall", "cover", "neu_hold", "gender_move"],
        "not_scored": ["exam_score", "leak_frac", "c+", "p%"],
        "gates": {
            "lyric_recall_min": LYRIC_RECALL_MIN,
            "cover_min": PLUS_COVER_MIN,
            "neu_hold_min": PLUS_NEU_HOLD_MIN,
            "gender_move_min": GENDER_MOVE_MIN,
            "continuation_floor": EXAM_ROLL_OVERLAP,
        },
        "recipes": [c["name"] for c in LYRIC_RECIPES],
        "cells": list(LYRIC_CELLS),
        "steps": args.steps,
        "seed": args.seed,
        "verdict": {
            k: v
            for k, v in verdict.items()
            if k not in {"last_hidden_blind", "existing_ood"}
        },
        "rank": ranked,
        "rows": table,
    }
    (args.out / "metrics.json").write_text(
        json.dumps(blob, indent=2, default=str) + "\n", encoding="utf-8"
    )
    plot_lyric_orth(table, args.out / "lyric-orth-scale.png")
    write_markdown(table, verdict, ranked, _REPO / "docs" / "lm-lyric-orth.md")
    print(
        f"wrote {args.out}  orth_beats_split={verdict.get('orth_beats_split')} "
        f"want_box={any(r.get('want_box') for r in ranked if r['name']=='faithful_plus_neu_orth')}"
    )


if __name__ == "__main__":
    main()
