#!/usr/bin/env python3
"""Compile every scored 2-D / high-D / sheet recipe into one gated table."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from analysis.slider2d.scoreboard import (
    FAILS,
    WORKS,
    WORKS_GENDER_ONLY,
    collect_scoreboard,
    floatable_row,
    gates_blob,
    sort_rows,
)


DEFAULT_OUT = _REPO / "docs" / "lm-2d-scoreboard"


def _fmt(value, spec: str, empty: str = "N/A") -> str:
    if value is None:
        return empty
    return format(float(value), spec)


def _verdict_md(verdict: str) -> str:
    if verdict == WORKS:
        return "**works**"
    if verdict == WORKS_GENDER_ONLY:
        return "works-on-gender-only"
    return "**fails**"


TABLE_HEADER = (
    "| recipe | leftover leak | on-sheet | kept | off-sheet | argmax | "
    "swing | pair-odd cos *(log)* | ±1 *(log)* | intended cos | "
    "c+ | perc | rich-kept | compiled |\n"
    "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|"
)


def _table_md(row: dict) -> str:
    return (
        f"| `{row['id']}` | {_fmt(row['leftover_leak'], '+.3f')} | "
        f"{_fmt(row['on_sheet'], '.3f')} | {_fmt(row['on_sheet_kept'], '.3f')} | "
        f"{_fmt(row['off_sheet'], '.3f')} | {_fmt(row['argmax_on_sheet'], '.2f')} | "
        f"{_fmt(row['swing_kept'], '.2f')} | {_fmt(row['pair_odd_cos'], '+.3f')} | "
        f"{_fmt(row['collapse'], '+.3f')} | {_fmt(row['intended_cos'], '+.3f')} | "
        f"{_fmt(row['trainer_c_plus'], '+.3f')} | {_fmt(row['perc'], '.0f')} | "
        f"{_fmt(row['rich_kept'], '.2f')} | {_verdict_md(row['compiled'])} |"
    )


def plot_scoreboard(rows: list[dict], path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8.4, 5.2))
    colors = {
        WORKS: "#1e8449",
        WORKS_GENDER_ONLY: "#b9770e",
        FAILS: "#c0392b",
    }
    for verdict, color in colors.items():
        pts = [r for r in rows if r["compiled"] == verdict]
        xs = [0.0 if r["leftover_leak"] is None else r["leftover_leak"] for r in pts]
        ys = [0.0 if r["on_sheet_kept"] is None else r["on_sheet_kept"] for r in pts]
        ax.scatter(xs, ys, c=color, s=42, label=verdict, zorder=3)
        for row, x, y in zip(pts, xs, ys):
            ax.annotate(row["id"], (x, y), fontsize=6.4, xytext=(4, 3), textcoords="offset points")
    ax.axvline(0.20, color="#7f8c8d", ls=":", lw=0.9)
    ax.axhline(0.90, color="#7f8c8d", ls=":", lw=0.9)
    ax.set_xlabel("leftover leak  (unused mix / BPM / gender)")
    ax.set_ylabel("on-sheet kept  (N/A plotted at 0)")
    ax.set_title("compiled gate: leak small and, when a sheet exists, stay on it")
    ax.grid(alpha=0.25)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def write_report(rows: list[dict], blob: dict, path: Path) -> None:
    gates = blob["gates"]
    winners = [r for r in rows if r["compiled"] == WORKS]
    gender_only = [r for r in rows if r["compiled"] == WORKS_GENDER_ONLY]
    fails = [r for r in rows if r["compiled"] == FAILS]
    lines = [
        "# 2-D / high-D / sheet scoreboard",
        "",
        "Generated by `analysis/slider2d/run_lm_scoreboard.py`. CPU only, no Hub,",
        "no GPU, no Music 3 weights. Does not change the live trainer default.",
        "",
        "Every other cell in this repo scores one question. This page joins",
        "those real fixture numbers into **one table** and applies one gate.",
        "It does not invent a loss.",
        "",
        "## The compiled gate",
        "",
        gates["prose"],
        "",
        f"- leftover leak lock: `{gates['leak_lock']}`",
        f"- on-sheet kept: `≥ {gates['sheet_lock']}`",
        f"- off-sheet mass: `≤ {gates['garble_max']}`",
        f"- argmax-on-sheet: `{gates['argmax_lock']:g}`",
        f"- concept swing kept: `≥ {gates['swing_floor']}`",
        f"- pair-odd cos scored: `{gates['pair_odd_cos_scored']}`",
        f"- ±1 collapse scored: `{gates['collapse_scored']}`",
        "",
        "A missing sheet column is N/A, not a free pass for a midpoint",
        "teacher: those rows inherit the leftover sheet of `t± = h0 ± a`",
        "because deleting `c` is a fact about the target point, not the",
        "hidden width. High pair-odd cos cannot move a row up the table.",
        "",
        "## Short verdict",
        "",
    ]
    if winners:
        names = ", ".join(f"`{r['id']}`" for r in winners)
        lines.append(
            f"**Works, in order:** {names}. Both keep leftover leak at 0 "
            "and stay on the caption sheet with the concept swing intact. "
            "They share the target (ê-cleaned real poles), not the loss."
        )
    else:
        lines.append("No recipe passed the compiled gate.")
    if gender_only:
        names = ", ".join(f"`{r['id']}`" for r in gender_only)
        lines.append(
            f"**Works on gender only:** {names}. On-sheet on a clean pair; "
            "unused ê still rides along on leftover captions."
        )
    lines += [
        "",
        f"**Fails:** {len(fails)} recipes, including the live midpoint "
        "(`pair_odd_midpoint` / `--lm_target v9`), `#20` "
        "`pair_odd_sub_e` (leak 0, off-sheet), hub, hold-ê, and short-û "
        "project. A perfect pair-odd lock is the failure mode.",
        "",
        "## Table",
        "",
        "Sorted by compiled verdict, then leftover leak, then on-sheet mass.",
        "Pair-odd cos and ±1 are **logged, never scored**.",
        "",
        TABLE_HEADER,
    ]
    lines += [_table_md(r) for r in rows]
    lines += [
        "",
        "![leak vs on-sheet kept](lm-2d-scoreboard/scoreboard.png)",
        "",
        "## What each row is",
        "",
    ]
    for row in rows:
        extra = []
        if row.get("content_cos") is not None:
            extra.append(f"content-cos {_fmt(row['content_cos'], '+.3f')}")
        if row.get("polarity_distinct") is not None:
            extra.append(f"polarity {_fmt(row['polarity_distinct'], '+.3f')}")
        if row.get("trainer_c_plus_distinct") is not None:
            extra.append(f"c+ distinct {_fmt(row['trainer_c_plus_distinct'], '+.3f')}")
        if row.get("loss") is not None:
            extra.append(f"loss {_fmt(row['loss'], '.3f')}")
        suffix = f" ({'; '.join(extra)})" if extra else ""
        lines.append(
            f"- `{row['id']}` — {row['label']}. {row['notes']} "
            f"Fixture: {row['fixture']}.{suffix}"
        )
    lines += [
        "",
        "## Why pair-odd cos is not in the score",
        "",
        "On the leftover sheet, `v9_hidden` prints `cos(d+, a) = +1.000`",
        "and `cos(d+, d−) = −1.000` while keeping about a third of the",
        "caption's on-sheet mass. `faithful_sub_e` and",
        "`semantic_kl_sub_e` print worse pair-odd numbers and pass.",
        "`pair_odd_sub_e` drives leftover leak to 0 and stays off-sheet.",
        "The compiled sort therefore cannot use that cosine.",
        "",
        "## Related cells",
        "",
        "- [lm-sheet-goodhart.md](lm-sheet-goodhart.md) — the sheet readout",
        "  and the four locked recipes.",
        "- [lm-live-cells.md](lm-live-cells.md) — gender-like vs energy-like",
        "  hidden leak.",
        "- [lm-highd-leftover.md](lm-highd-leftover.md) — leftover ê, λ·D/2,",
        "  trainer c+.",
        "- [lm-rich-2d.md](lm-rich-2d.md) — project short û vs rich û.",
        "- [lm-faithful-2d.md](lm-faithful-2d.md) — raw poles vs attributes.",
        "- [lm-hold-overlap.md](lm-hold-overlap.md) — hold-ê raw vs ê_⊥û.",
        "",
        "## How to run",
        "",
        "```bash",
        "PYTHONPATH=. python analysis/slider2d/run_lm_scoreboard.py --out docs/lm-2d-scoreboard",
        "PYTHONPATH=. pytest tests/test_lm_2d_scoreboard.py -q",
        "```",
        "",
        "CPU only. No Hub, no GPU, no Music 3 weights.",
        "",
        f"Sheet seed `{blob['seed']}`, `{blob['sheet_steps']}` Adam steps; "
        f"other fixtures `{blob['other_steps']}` steps.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--sheet-steps", type=int, default=400)
    parser.add_argument("--other-steps", type=int, default=200)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)

    out = args.out
    out.mkdir(parents=True, exist_ok=True)
    rows = collect_scoreboard(
        sheet_steps=args.sheet_steps, other_steps=args.other_steps, seed=args.seed
    )
    rows = sort_rows(rows)
    blob = {
        "sheet_steps": args.sheet_steps,
        "other_steps": args.other_steps,
        "seed": args.seed,
        "gates": gates_blob(),
        "rows": [floatable_row(r) for r in rows],
        "live_default_unchanged": True,
    }
    (out / "metrics.json").write_text(json.dumps(blob, indent=2) + "\n", encoding="utf-8")
    plot_scoreboard(rows, out / "scoreboard.png")
    write_report(rows, blob, out.parent / "lm-2d-scoreboard.md")
    for row in rows:
        print(
            f"{row['compiled']:22s} {row['id']:28s} "
            f"leak={_fmt(row['leftover_leak'], '+.3f')} "
            f"sheet={_fmt(row['on_sheet_kept'], '.3f')} "
            f"cos={_fmt(row['pair_odd_cos'], '+.3f')}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
